#!/usr/bin/env python3
"""
Generates the initial messy workspace for the Flutter GetX architecture task.
Creates a partially broken project structure that the agent must fix and extend.
"""

import os
import random
from pathlib import Path

random.seed(42)

workspace = Path("/workspace")

# ── 1. Create the main lib/ entry point ──────────────────────────────────────
lib = workspace / "lib"
lib.mkdir(parents=True, exist_ok=True)

(lib / "main.dart").write_text("""import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Logistics App',
      home: Container(),
    );
  }
}
""")

# ── 2. Create a BADLY NAMED existing module (violations agent must fix) ───────
# Violation 1: folder name uses camelCase instead of snake_case
# Violation 2: view class uses "Widget" suffix instead of "Page" or "View"
# Violation 3: logic extends GetxController directly, not BaseController
modules = lib / "modules"
bad_module = modules / "deliveryReport"   # <-- camelCase: WRONG
bad_module.mkdir(parents=True, exist_ok=True)

(bad_module / "deliveryReportBinding.dart").write_text("""import 'package:get/get.dart';
import 'deliveryReportLogic.dart';

class DeliveryReportBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<DeliveryReportLogic>(() => DeliveryReportLogic());
  }
}
""")

(bad_module / "deliveryReportLogic.dart").write_text("""import 'package:get/get.dart';
import 'deliveryReportState.dart';

// BUG: extends GetxController instead of BaseController
class DeliveryReportLogic extends GetxController {
  final DeliveryReportState state = DeliveryReportState();
}
""")

(bad_module / "deliveryReportState.dart").write_text("""class DeliveryReportState {
  DeliveryReportState();
}
""")

# Violation: class name ends with "Widget" not "Page" or "View"
(bad_module / "deliveryReportWidget.dart").write_text("""import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'deliveryReportLogic.dart';

// BUG: class name ends with Widget (should be Page or View)
class DeliveryReportWidget extends GetView<DeliveryReportLogic> {
  const DeliveryReportWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Delivery Report')),
      body: const Center(child: Text('Delivery Report')),
    );
  }
}
""")

# ── 3. Create a cross-module import violation (bonus distractor) ───────────────
# A fake auth module that incorrectly imports from deliveryReport
auth_module = modules / "auth"
auth_module.mkdir(parents=True, exist_ok=True)
(auth_module / "auth_logic.dart").write_text("""import 'package:flutter_app/shared/data/base_business/base_controller.dart';
// VIOLATION: direct cross-module import (should use routing instead)
import '../deliveryReport/deliveryReportLogic.dart';

class AuthLogic extends BaseController {
  void badCrossImport() {
    // This references another module directly - architecture violation
  }
}
""")
(auth_module / "auth_state.dart").write_text("""class AuthState {
  AuthState();
}
""")

# ── 4. Distractor files - simulate a real messy project ───────────────────────
# Miscellaneous files that exist but are irrelevant
(workspace / "pubspec.yaml").write_text("""name: logistics_app
description: A logistics mobile application
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
""")

(workspace / "pubspec.lock").write_text("# Generated by pub. Do not edit.\n")
(workspace / "README_old.txt").write_text("Old readme - ignore this file\n")
(workspace / ".gitignore").write_text(".dart_tool/\nbuild/\n*.g.dart\n")
(workspace / "analysis_options.yaml").write_text("""include: package:flutter_lints/flutter.yaml
""")

# Some test files as distractors
test_dir = workspace / "test"
test_dir.mkdir(exist_ok=True)
(test_dir / "widget_test.dart").write_text("""import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('placeholder test', (WidgetTester tester) async {
    expect(true, isTrue);
  });
}
""")

# Android / iOS stubs
android = workspace / "android" / "app" / "src" / "main"
android.mkdir(parents=True, exist_ok=True)
(android / "AndroidManifest.xml").write_text("""<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.logistics_app">
</manifest>
""")

ios = workspace / "ios" / "Runner"
ios.mkdir(parents=True, exist_ok=True)
(ios / "AppDelegate.swift").write_text("""import UIKit
import Flutter

@UIApplicationMain
class AppDelegate: FlutterAppDelegate {}
""")

# Extra distractor dart files in lib root
(lib / "app_config.dart").write_text("""// App-wide configuration constants
const String appName = 'LogisticsApp';
const String apiBaseUrl = 'https://api.example.com';
""")

(lib / "theme.dart").write_text("""import 'package:flutter/material.dart';

final ThemeData appTheme = ThemeData(
  primarySwatch: Colors.blue,
);
""")

# A partial/incomplete core directory that is missing required subdirectories
core_partial = lib / "core"
core_partial.mkdir(exist_ok=True)
# Only 'utils' exists — missing config, constants, navigation, services, widgets
utils_dir = core_partial / "utils"
utils_dir.mkdir(exist_ok=True)
(utils_dir / "date_formatter.dart").write_text("""String formatDate(DateTime dt) => dt.toIso8601String();
""")

# A partial/incomplete shared directory missing required subdirs
shared_partial = lib / "shared"
shared_partial.mkdir(exist_ok=True)
# Only domain exists — missing data/base_business, data/local, data/download, data/upload
domain_dir = shared_partial / "domain"
domain_dir.mkdir(exist_ok=True)
(domain_dir / "events.dart").write_text("""// Domain events placeholder
abstract class DomainEvent {}
""")

print("Workspace initialized successfully.")
print("Violations introduced:")
print("  - lib/modules/deliveryReport/ (camelCase folder name)")
print("  - deliveryReportLogic.dart extends GetxController (should be BaseController)")
print("  - deliveryReportWidget.dart class ends with Widget (should be Page or View)")
print("  - auth_logic.dart has cross-module import violation")
print("Missing structure:")
print("  - core/: missing config, constants, navigation, services, widgets")
print("  - shared/: missing data/base_business, data/local, data/download, data/upload")
print("  - modules/shipment_tracking/ does not exist")
print("  - modules/warehouse_inventory/ does not exist")