import os
import random
import string
import hashlib
import json
from pathlib import Path

random.seed(42)

workspace = Path("/workspace")
workspace.mkdir(parents=True, exist_ok=True)

# --- Create deeply nested distractor directory structure ---
distractor_dirs = [
    "compliance/reports/2024/Q1",
    "compliance/reports/2024/Q2",
    "compliance/reports/2024/Q3",
    "compliance/backups/incremental",
    "compliance/backups/full",
    "sysmon/alerts/critical",
    "sysmon/alerts/warning",
    "sysmon/metrics/cpu",
    "sysmon/metrics/disk",
    "infra/configs/network",
    "infra/configs/firewall",
    "infra/logs/nginx",
    "infra/logs/postgres",
    "audit_tools/legacy",
    "audit_tools/scripts",
]

for d in distractor_dirs:
    (workspace / d).mkdir(parents=True, exist_ok=True)

# --- Create distractor files ---
distractor_files = {
    "compliance/reports/2024/Q1/hipaa_summary.txt": "HIPAA Compliance Report Q1 2024\nStatus: Partial\nItems pending: 3\n",
    "compliance/reports/2024/Q2/hipaa_summary.txt": "HIPAA Compliance Report Q2 2024\nStatus: Complete\n",
    "compliance/reports/2024/Q3/draft_notes.txt": "Draft notes - do not distribute\nAudit trail review needed\n",
    "compliance/backups/incremental/backup_20240901.tar.gz.manifest": "backup_manifest_v2\nfiles: 1423\nsize_bytes: 8472938\n",
    "compliance/backups/full/backup_20240101.tar.gz.manifest": "backup_manifest_v2\nfiles: 9821\nsize_bytes: 392847102\n",
    "sysmon/alerts/critical/alert_001.json": json.dumps({
        "alert_id": "C-2024-0091",
        "severity": "CRITICAL",
        "message": "Unauthorized access attempt detected",
        "timestamp": "2024-09-12T03:22:11Z"
    }),
    "sysmon/alerts/warning/warn_042.json": json.dumps({
        "alert_id": "W-2024-0042",
        "severity": "WARNING",
        "message": "Disk usage above 80%",
        "timestamp": "2024-09-15T14:05:33Z"
    }),
    "sysmon/metrics/cpu/cpu_usage_20240915.csv": "timestamp,usage_pct\n2024-09-15T00:00:00Z,12.3\n2024-09-15T00:01:00Z,14.1\n",
    "sysmon/metrics/disk/disk_usage_20240915.csv": "mount,used_gb,total_gb\n/,45.2,100.0\n/var,12.1,50.0\n",
    "infra/configs/network/interfaces.conf": "# Network interface configuration\nauto eth0\niface eth0 inet dhcp\n",
    "infra/configs/firewall/rules.v4": "*filter\n:INPUT DROP [0:0]\n:FORWARD DROP [0:0]\n:OUTPUT ACCEPT [0:0]\nCOMMIT\n",
    "infra/logs/nginx/access.log.sample": '127.0.0.1 - - [15/Sep/2024:10:00:00 +0000] "GET /health HTTP/1.1" 200 12\n',
    "infra/logs/postgres/pg_slow_queries.log": "2024-09-15 03:12:44 UTC [1234]: LOG duration: 3201.234 ms SELECT * FROM audit_events WHERE...\n",
    "audit_tools/legacy/audit_parser_v1.py": "# Legacy audit parser - deprecated\n# Use clauditor instead\nimport sys\nprint('Deprecated: use clauditor digest')\n",
    "audit_tools/scripts/generate_report.sh": "#!/bin/bash\n# Placeholder - incomplete script\necho 'TODO: wire up to audit backend'\nexit 1\n",
}

for filepath, content in distractor_files.items():
    full_path = workspace / filepath
    full_path.parent.mkdir(parents=True, exist_ok=True)
    full_path.write_text(content)

# --- Create a misleading fake digest file to trap naive agents ---
fake_digest_content = """# Audit Digest (INCOMPLETE)

This file was auto-generated by a legacy script.
Do NOT use for compliance purposes.

Log file: /var/log/sysaudit.log (WRONG PATH)
Key: /etc/audit/key (WRONG PATH)

Hash: 0000000000000000000000000000000000000000000000000000000000000000
"""
(workspace / "audit_tools/legacy/fake_audit_digest.md").write_text(fake_digest_content)

# --- Write a task context file (business context only, no hints) ---
task_context = {
    "department": "Healthcare IT Security",
    "ticket_id": "SEC-2024-1147",
    "requestor": "Chief Compliance Officer",
    "description": (
        "Per HIPAA §164.312(b), we require a tamper-evident audit digest of all "
        "filesystem watchdog events for the current audit cycle. "
        "The security watchdog tool has been installed under /opt/clauditor. "
        "Output must be in Markdown format."
    ),
    "output_filename": "audit_digest.md",
    "priority": "CRITICAL"
}
(workspace / "task_context.json").write_text(json.dumps(task_context, indent=2))

print("Workspace generated successfully.")
print(f"Workspace contents: {list(workspace.rglob('*'))[:20]}...")