#!/usr/bin/env python3
"""
Generates the full workspace sandbox for the client-dashboard benchmark task.
"""
import os
import json
import random
from pathlib import Path
from decimal import Decimal

random.seed(42)

workspace = Path("/workspace")

# ── Directory skeleton ──────────────────────────────────────────────────────
dirs = [
    "scripts/pipelines",
    "scripts/utils",
    "scripts/reports",
    "skills/client-dashboard",
    "skills/bank-reconciliation",
    "skills/pl-quick-compare",
    ".cache/client-dashboard",
    ".cache/pl-quick-compare",
    "clients/ember-oak",
    "clients/pine-ridge",
    "clients/sunflower-cafe",
    "logs",
    "docs",
    "config",
]
for d in dirs:
    (workspace / d).mkdir(parents=True, exist_ok=True)

# ── Distractor files ────────────────────────────────────────────────────────
distractor_files = {
    "docs/pipeline_overview.md": "# Pipeline Overview\nSee individual SKILL.md files for details.\n",
    "docs/qbo_setup.md": "# QBO Setup\nContact IT for authentication credentials.\n",
    "config/global_settings.json": json.dumps({"timezone": "America/New_York", "currency": "USD", "version": "1.0"}),
    "logs/bank-rec-2026-03.log": "Bank rec completed successfully for pine-ridge 2026-03\n",
    "logs/pl-compare-2026-03.log": "P&L compare completed for sunflower-cafe 2026-03\n",
    "scripts/utils/decimal_helpers.py": "from decimal import Decimal\ndef to_d(v): return Decimal(str(v))\n",
    "scripts/utils/excel_helpers.py": "# Excel formatting utilities\nPASS = 'green'\nWARN = 'yellow'\nFAIL = 'red'\n",
    "scripts/reports/monthly_summary_template.xlsx.placeholder": "placeholder — real template is generated by pipeline\n",
    "clients/pine-ridge/notes.txt": "Pine Ridge client — restaurant group, 4 locations\nMonthly close: 5th business day\n",
    "clients/sunflower-cafe/notes.txt": "Sunflower Cafe — bakery, QBO connected since 2024-01\n",
    "clients/ember-oak/notes.txt": "Ember & Oak Bistro — fine dining, single location, QBO connected 2025-11\n",
    ".cache/pl-quick-compare/pine-ridge.json": json.dumps({"month": "2026-03", "net_margin": 8.2}),
    ".cache/pl-quick-compare/sunflower-cafe.json": json.dumps({"month": "2026-03", "gross_margin": 61.4}),
    "skills/bank-reconciliation/SKILL.md": "# Bank Reconciliation\nRun before client dashboard.\n",
    "skills/pl-quick-compare/SKILL.md": "# P&L Quick Compare\nVariance analysis — not a substitute for client dashboard.\n",
    "config/client_roster.json": json.dumps({
        "clients": ["pine-ridge", "sunflower-cafe", "ember-oak"],
        "active": True
    }, indent=2),
}
for rel_path, content in distractor_files.items():
    p = workspace / rel_path
    p.write_text(content)

# ── The actual pipeline script (client-dashboard.py) ────────────────────────
# This is a realistic, working implementation. The agent must:
#   1. Add the ember-oak CLIENT_CONFIGS block (with correct Decimal thresholds)
#   2. Ensure the CDC cache exists with prior-run data
#   3. Run the pipeline with correct CLI args
#   4. Verify the output workbook

pipeline_script = r'''#!/usr/bin/env python3
"""Client Dashboard / KPI Report Pipeline"""
import argparse
import json
import os
import sys
from datetime import datetime, date
from decimal import Decimal, ROUND_HALF_UP, InvalidOperation
from pathlib import Path
import calendar

try:
    import openpyxl
    from openpyxl import Workbook
    from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    print("ERROR: openpyxl not installed. Run: pip install openpyxl")
    sys.exit(1)

# ─────────────────────────────────────────────────────────────
# CLIENT CONFIGS  — add new clients here
# ─────────────────────────────────────────────────────────────
CLIENT_CONFIGS = {
    "pine-ridge": {
        "company_name": "Pine Ridge Restaurant Group",
        "industry": "Restaurant / Hospitality",
        "has_ar": True,
        "has_headcount": True,
        "kpis_enabled": ["revenue_mom", "gross_margin", "net_margin", "opex_ratio", "current_ratio"],
        "thresholds": {
            "revenue_mom":    {"green": (Decimal("3"), None),   "yellow": (Decimal("0"), Decimal("3"))},
            "gross_margin":   {"green": (Decimal("60"), None),  "yellow": (Decimal("50"), Decimal("60"))},
            "net_margin":     {"green": (Decimal("8"), None),   "yellow": (Decimal("4"), Decimal("8"))},
            "opex_ratio":     {"green": (None, Decimal("35")),  "yellow": (Decimal("35"), Decimal("45"))},
            "current_ratio":  {"green": (Decimal("1.5"), None), "yellow": (Decimal("1.0"), Decimal("1.5"))},
        },
        "watch_items": ["Monitor food cost variance monthly", "Review labor as % of revenue quarterly"],
        "benchmarks": {"gross_margin": Decimal("62"), "net_margin": Decimal("9")},
        "benchmark_source": "NRA 2024 Industry Report",
    },
    "sunflower-cafe": {
        "company_name": "Sunflower Cafe & Bakery",
        "industry": "Food & Beverage / Retail",
        "has_ar": False,
        "has_headcount": False,
        "kpis_enabled": ["revenue_mom", "gross_margin", "net_margin", "retail_pct"],
        "thresholds": {
            "revenue_mom":  {"green": (Decimal("2"), None),  "yellow": (Decimal("0"), Decimal("2"))},
            "gross_margin": {"green": (Decimal("58"), None), "yellow": (Decimal("48"), Decimal("58"))},
            "net_margin":   {"green": (Decimal("6"), None),  "yellow": (Decimal("2"), Decimal("6"))},
            "retail_pct":   {"green": (Decimal("30"), None), "yellow": (Decimal("20"), Decimal("30"))},
        },
        "watch_items": ["Retail mix trending down — review product lineup"],
        "benchmarks": {"gross_margin": Decimal("60")},
        "benchmark_source": "IBISWorld Bakery 2024",
    },
    # NEW CLIENT CONFIGS GO HERE — agent must add ember-oak block
}

# ─────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────
def to_d(v):
    """Convert any numeric to Decimal safely."""
    try:
        return Decimal(str(v))
    except InvalidOperation:
        return Decimal("0")

def pct(numerator, denominator):
    if denominator == 0:
        return Decimal("0")
    return (to_d(numerator) / to_d(denominator) * 100).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

def ratio(numerator, denominator):
    if denominator == 0:
        return Decimal("0")
    return (to_d(numerator) / to_d(denominator)).quantize(Decimal("0.0001"), rounding=ROUND_HALF_UP)

def mom_growth(curr, prior):
    if prior == 0:
        return Decimal("0")
    return ((to_d(curr) - to_d(prior)) / to_d(prior) * 100).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

# ─────────────────────────────────────────────────────────────
# QBO DATA FETCHING  (mocked via JSON fixture if available)
# ─────────────────────────────────────────────────────────────
def fetch_qbo_data(slug, month_str, sandbox=False):
    """
    Fetch financial data for slug/month.
    Looks for fixture at: .cache/qbo-fixtures/{slug}/{month_str}.json
    Falls back to zeros if fixture missing (real impl would call QBO CLI).
    """
    fixture_path = Path(f".cache/qbo-fixtures/{slug}/{month_str}.json")
    if fixture_path.exists():
        raw = json.loads(fixture_path.read_text())
        # Coerce all numeric values to Decimal
        def coerce(obj):
            if isinstance(obj, dict):
                return {k: coerce(v) for k, v in obj.items()}
            if isinstance(obj, list):
                return [coerce(i) for i in obj]
            if isinstance(obj, (int, float)):
                return to_d(obj)
            return obj
        return coerce(raw)
    else:
        # Return zero-filled structure
        return {
            "revenue": to_d(0), "prior_revenue": to_d(0), "yoy_revenue": to_d(0),
            "gross_profit": to_d(0), "net_income": to_d(0), "total_opex": to_d(0),
            "interest_expense": to_d(0), "current_assets": to_d(0), "current_liabilities": to_d(0),
            "inventory": to_d(0), "total_liabilities": to_d(0), "total_equity": to_d(0),
            "ar": to_d(0), "ap": to_d(0), "cash": to_d(0), "monthly_burn": to_d(0),
            "retail_revenue": to_d(0), "cogs": to_d(0),
            "days_in_month": to_d(calendar.monthrange(int(month_str[:4]), int(month_str[5:7]))[1]),
            "trend_6mo": [],  # list of dicts for prior 5 months
        }

# ─────────────────────────────────────────────────────────────
# KPI COMPUTATION
# ─────────────────────────────────────────────────────────────
def compute_kpis(data, config, month_str):
    enabled = config.get("kpis_enabled", [])
    kpis = {}

    rev = data["revenue"]
    days = data["days_in_month"]

    if "revenue_mom" in enabled:
        kpis["revenue_mom"] = {
            "label": "Revenue MoM Growth",
            "value": mom_growth(rev, data["prior_revenue"]),
            "unit": "%",
            "formula": "(curr_rev - prior_rev) / prior_rev × 100",
        }
    if "revenue_yoy" in enabled:
        kpis["revenue_yoy"] = {
            "label": "Revenue YoY Growth",
            "value": mom_growth(rev, data["yoy_revenue"]),
            "unit": "%",
            "formula": "(curr_rev - yoy_rev) / yoy_rev × 100",
        }
    if "gross_margin" in enabled:
        kpis["gross_margin"] = {
            "label": "Gross Margin %",
            "value": pct(data["gross_profit"], rev),
            "unit": "%",
            "formula": "gross_profit / revenue × 100",
        }
    if "net_margin" in enabled:
        kpis["net_margin"] = {
            "label": "Net Margin %",
            "value": pct(data["net_income"], rev),
            "unit": "%",
            "formula": "net_income / revenue × 100",
        }
    if "opex_ratio" in enabled:
        kpis["opex_ratio"] = {
            "label": "OpEx Ratio",
            "value": pct(data["total_opex"], rev),
            "unit": "%",
            "formula": "total_opex / revenue × 100",
        }
    if "interest_expense_ratio" in enabled:
        kpis["interest_expense_ratio"] = {
            "label": "Interest Expense Ratio",
            "value": pct(data["interest_expense"], rev),
            "unit": "%",
            "formula": "interest_expense / revenue × 100",
        }
    if "current_ratio" in enabled:
        kpis["current_ratio"] = {
            "label": "Current Ratio",
            "value": ratio(data["current_assets"], data["current_liabilities"]),
            "unit": "x",
            "formula": "current_assets / current_liabilities",
        }
    if "quick_ratio" in enabled:
        kpis["quick_ratio"] = {
            "label": "Quick Ratio",
            "value": ratio(data["current_assets"] - data["inventory"], data["current_liabilities"]),
            "unit": "x",
            "formula": "(current_assets - inventory) / current_liabilities",
        }
    if "debt_to_equity" in enabled:
        kpis["debt_to_equity"] = {
            "label": "Debt-to-Equity",
            "value": ratio(data["total_liabilities"], data["total_equity"]),
            "unit": "x",
            "formula": "total_liabilities / total_equity",
        }
    if "dso" in enabled and rev > 0:
        kpis["dso"] = {
            "label": "DSO",
            "value": (to_d(data["ar"]) / (rev / days)).quantize(Decimal("0.1"), rounding=ROUND_HALF_UP),
            "unit": "days",
            "formula": "ar / (revenue / days)",
        }
    if "dpo" in enabled and data["cogs"] > 0:
        kpis["dpo"] = {
            "label": "DPO",
            "value": (to_d(data["ap"]) / (data["cogs"] / days)).quantize(Decimal("0.1"), rounding=ROUND_HALF_UP),
            "unit": "days",
            "formula": "ap / (cogs / days)",
        }
    if "cash_runway" in enabled and data["monthly_burn"] > 0:
        kpis["cash_runway"] = {
            "label": "Cash Runway",
            "value": ratio(data["cash"], data["monthly_burn"]),
            "unit": "months",
            "formula": "cash / monthly_burn",
        }
    if "retail_pct" in enabled:
        kpis["retail_pct"] = {
            "label": "Retail % of Revenue",
            "value": pct(data["retail_revenue"], rev),
            "unit": "%",
            "formula": "retail_revenue / total_revenue × 100",
        }
    return kpis

# ─────────────────────────────────────────────────────────────
# TRAFFIC LIGHT SCORING
# ─────────────────────────────────────────────────────────────
GREEN  = "GREEN"
YELLOW = "YELLOW"
RED    = "RED"
NA     = "N/A"

FILL_GREEN  = PatternFill("solid", fgColor="00B050")
FILL_YELLOW = PatternFill("solid", fgColor="FFFF00")
FILL_RED    = PatternFill("solid", fgColor="FF0000")
FILL_GREY   = PatternFill("solid", fgColor="D3D3D3")
FILL_HEADER = PatternFill("solid", fgColor="2F4F4F")

def score_kpi(key, value, config):
    thresholds = config.get("thresholds", {})
    if key not in thresholds:
        return NA
    t = thresholds[key]
    green_lo, green_hi = t["green"]
    yellow_lo, yellow_hi = t["yellow"]

    def in_band(lo, hi, v):
        lo_ok = (lo is None) or (v >= lo)
        hi_ok = (hi is None) or (v <= hi)
        return lo_ok and hi_ok

    if in_band(green_lo, green_hi, value):
        return GREEN
    elif in_band(yellow_lo, yellow_hi, value):
        return YELLOW
    else:
        return RED

def score_fill(score):
    return {GREEN: FILL_GREEN, YELLOW: FILL_YELLOW, RED: FILL_RED, NA: FILL_GREY}[score]

# ─────────────────────────────────────────────────────────────
# SPARKLINES
# ─────────────────────────────────────────────────────────────
ARROW_MAP = [
    (15,  "↑↑"),
    (5,   "↑"),
    (2,   "↗"),
    (-2,  "→"),
    (-5,  "↘"),
    (-15, "↓"),
]

def pct_change_arrow(pct_val):
    """Map % change to direction arrow."""
    v = float(pct_val)
    for threshold, arrow in ARROW_MAP:
        if v >= threshold:
            return arrow
    return "↓↓"

BLOCK_CHARS = ["_", "▁", "▃", "▅", "▇", "█"]

def value_to_block(v, max_v, min_v):
    if max_v == min_v:
        return "▃"
    ratio_val = (float(v) - float(min_v)) / (float(max_v) - float(min_v))
    idx = min(int(ratio_val * (len(BLOCK_CHARS) - 1) + 0.5), len(BLOCK_CHARS) - 1)
    return BLOCK_CHARS[idx]

def build_sparkline(values_6mo):
    """Build arrow sparkline string from list of 6 Decimal values (oldest→newest)."""
    if len(values_6mo) < 2:
        return "→"
    arrows = []
    for i in range(1, len(values_6mo)):
        prev = values_6mo[i-1]
        curr = values_6mo[i]
        if prev == 0:
            arrows.append("→")
        else:
            chg = mom_growth(curr, prev)
            arrows.append(pct_change_arrow(chg))
    return " ".join(arrows)

def build_block_sparkline(values_6mo):
    """Build block-char sparkline from list of 6 Decimal values."""
    if not values_6mo:
        return "_"
    max_v = max(float(v) for v in values_6mo)
    min_v = min(float(v) for v in values_6mo)
    return "".join(value_to_block(v, max_v, min_v) for v in values_6mo)

# ─────────────────────────────────────────────────────────────
# CDC  (Change Data Capture)
# ─────────────────────────────────────────────────────────────
CACHE_DIR = Path(".cache/client-dashboard")

def load_prior_cache(slug):
    p = CACHE_DIR / f"{slug}.json"
    if p.exists():
        raw = json.loads(p.read_text())
        return {k: to_d(v) for k, v in raw.items()}
    return None

def save_cache(slug, kpis):
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    snapshot = {k: str(v["value"]) for k, v in kpis.items()}
    (CACHE_DIR / f"{slug}.json").write_text(json.dumps(snapshot, indent=2))

def build_cdc_rows(prior, current_kpis):
    """Return list of CDC row dicts."""
    rows = []
    for key, kpi in current_kpis.items():
        curr_val = kpi["value"]
        label = kpi["label"]
        if prior and key in prior:
            prior_val = prior[key]
            delta = (curr_val - prior_val).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
            if prior_val != 0:
                pct_chg = ((delta / prior_val) * 100).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
            else:
                pct_chg = Decimal("0")
            direction = "Improved" if delta > 0 else ("Declined" if delta < 0 else "Unchanged")
            rows.append({
                "label": label,
                "prior": str(prior_val),
                "current": str(curr_val),
                "delta": str(delta),
                "pct_change": str(pct_chg),
                "direction": direction,
            })
        else:
            rows.append({
                "label": label,
                "prior": "—",
                "current": str(curr_val),
                "delta": "—",
                "pct_change": "—",
                "direction": "First run",
            })
    return rows

# ─────────────────────────────────────────────────────────────
# EXCEL WORKBOOK BUILDER
# ─────────────────────────────────────────────────────────────
def style_header_row(ws, row, num_cols):
    for col in range(1, num_cols + 1):
        cell = ws.cell(row=row, column=col)
        cell.fill = FILL_HEADER
        cell.font = Font(color="FFFFFF", bold=True)

def add_footer(ws, source):
    ws.append([])
    ws.append([f"Benchmark source: {source}"])

def build_workbook(slug, month_str, config, kpis, cdc_rows, data):
    wb = Workbook()

    company = config["company_name"]
    industry = config["industry"]
    benchmarks = config.get("benchmarks", {})
    bench_src = config.get("benchmark_source", "N/A")
    watch_items = config.get("watch_items", [])

    # ── Tab 1: Executive Summary ──────────────────────────────
    ws1 = wb.active
    ws1.title = "Executive Summary"
    ws1.append([f"Executive KPI Dashboard — {company}", "", "", month_str])
    ws1.append([f"Industry: {industry}"])
    ws1.append([])
    ws1.append(["KPI", "Value", "Unit", "Score", "Benchmark"])
    style_header_row(ws1, 4, 5)
    for key, kpi in kpis.items():
        score = score_kpi(key, kpi["value"], config)
        bench = str(benchmarks.get(key, "—"))
        row_idx = ws1.max_row + 1
        ws1.append([kpi["label"], str(kpi["value"]), kpi["unit"], score, bench])
        ws1.cell(row=row_idx, column=4).fill = score_fill(score)
    add_footer(ws1, bench_src)

    # ── Tab 2: KPI Scorecard ──────────────────────────────────
    ws2 = wb.create_sheet("KPI Scorecard")
    ws2.append([f"KPI Scorecard — {company} — {month_str}"])
    ws2.append([])
    ws2.append(["KPI", "Value", "Unit", "Formula", "Score", "Green Band", "Yellow Band"])
    style_header_row(ws2, 3, 7)
    for key, kpi in kpis.items():
        score = score_kpi(key, kpi["value"], config)
        thr = config.get("thresholds", {}).get(key, {})
        green = thr.get("green", (None, None))
        yellow = thr.get("yellow", (None, None))
        green_str = f"{green[0]}–{green[1]}" if green else "—"
        yellow_str = f"{yellow[0]}–{yellow[1]}" if yellow else "—"
        row_idx = ws2.max_row + 1
        ws2.append([kpi["label"], str(kpi["value"]), kpi["unit"], kpi.get("formula", ""), score, green_str, yellow_str])
        ws2.cell(row=row_idx, column=5).fill = score_fill(score)
    add_footer(ws2, bench_src)

    # ── Tab 3: Trends ─────────────────────────────────────────
    ws3 = wb.create_sheet("Trends")
    ws3.append([f"6-Month KPI Trends — {company}"])
    ws3.append([])
    ws3.append(["KPI", "Trend (Arrows)", "Trend (Blocks)", "Current Value"])
    style_header_row(ws3, 3, 4)
    trend_data = data.get("trend_6mo", [])
    for key, kpi in kpis.items():
        if trend_data:
            vals = [to_d(m.get(key, 0)) for m in trend_data] + [kpi["value"]]
        else:
            vals = [kpi["value"]]
        arrow_spark = build_sparkline(vals)
        block_spark = build_block_sparkline(vals)
        ws3.append([kpi["label"], arrow_spark, block_spark, str(kpi["value"])])
    add_footer(ws3, bench_src)

    # ── Tab 4: Cash Position ──────────────────────────────────
    ws4 = wb.create_sheet("Cash Position")
    ws4.append([f"Cash Position — {company} — {month_str}"])
    ws4.append([])
    ws4.append(["Metric", "Value"])
    style_header_row(ws4, 3, 2)
    ws4.append(["Cash Balance", str(data["cash"])])
    ws4.append(["Current Assets", str(data["current_assets"])])
    ws4.append(["Current Liabilities", str(data["current_liabilities"])])
    if data["current_liabilities"] > 0:
        cr = ratio(data["current_assets"], data["current_liabilities"])
        ws4.append(["Current Ratio", str(cr)])
    if data["monthly_burn"] > 0:
        runway = ratio(data["cash"], data["monthly_burn"])
        ws4.append(["Cash Runway (months)", str(runway)])
    add_footer(ws4, bench_src)

    # ── Tab 5: Watch Items ────────────────────────────────────
    ws5 = wb.create_sheet("Watch Items")
    ws5.append([f"Watch Items — {company} — {month_str}"])
    ws5.append([])
    ws5.append(["#", "Watch Item"])
    style_header_row(ws5, 3, 2)
    for i, item in enumerate(watch_items, 1):
        ws5.append([i, item])
    add_footer(ws5, bench_src)

    # ── Tab 6: CDC Log ────────────────────────────────────────
    ws6 = wb.create_sheet("CDC Log")
    ws6.append([f"CDC Log — {company} — {month_str}"])
    ws6.append([])
    ws6.append(["KPI", "Prior", "Current", "Delta", "% Change", "Direction"])
    style_header_row(ws6, 3, 6)
    for row in cdc_rows:
        ws6.append([row["label"], row["prior"], row["current"], row["delta"], row["pct_change"], row["direction"]])

    return wb

# ─────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Client Dashboard KPI Report")
    parser.add_argument("--slug",    required=True,  help="Company slug")
    parser.add_argument("--month",   required=True,  help="Report month YYYY-MM")
    parser.add_argument("--out",     default=str(Path.home() / "Desktop"), help="Output directory")
    parser.add_argument("--sandbox", action="store_true", help="Use QBO sandbox")
    args = parser.parse_args()

    slug = args.slug
    month_str = args.month
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    if slug not in CLIENT_CONFIGS:
        print(f"ERROR: No config found for slug '{slug}'. Add to CLIENT_CONFIGS first.")
        sys.exit(1)

    config = CLIENT_CONFIGS[slug]
    print(f"Generating KPI Dashboard for {config['company_name']} — {month_str}")

    data = fetch_qbo_data(slug, month_str, sandbox=args.sandbox)
    kpis = compute_kpis(data, config, month_str)

    prior = load_prior_cache(slug)
    cdc_rows = build_cdc_rows(prior, kpis)

    wb = build_workbook(slug, month_str, config, kpis, cdc_rows, data)

    out_file = out_dir / f"KPI_Dashboard_{slug}_{month_str.replace('-', '_')}.xlsx"
    wb.save(str(out_file))
    save_cache(slug, kpis)

    print(f"Dashboard saved: {out_file}")
    print(f"CDC cache updated: .cache/client-dashboard/{slug}.json")
    print("Done.")

if __name__ == "__main__":
    main()
'''

(workspace / "scripts/pipelines/client-dashboard.py").write_text(pipeline_script)
os.chmod(workspace / "scripts/pipelines/client-dashboard.py", 0o755)

# ── QBO fixture data for ember-oak April 2026 ───────────────────────────────
qbo_fixture_dir = workspace / ".cache/qbo-fixtures/ember-oak"
qbo_fixture_dir.mkdir(parents=True, exist_ok=True)

# April 2026 financial data for ember-oak
fixture_data = {
    "revenue": 187500,
    "prior_revenue": 172000,       # March 2026
    "yoy_revenue": 155000,         # April 2025
    "gross_profit": 112500,        # gross_margin = 112500/187500 = 60.0%
    "net_income": 16875,           # net_margin = 16875/187500 = 9.0%
    "total_opex": 75937,           # opex_ratio ~= 40.5%
    "interest_expense": 1875,
    "current_assets": 145000,
    "current_liabilities": 88000,  # current_ratio = 145000/88000 ~= 1.6477
    "inventory": 22000,
    "total_liabilities": 210000,
    "total_equity": 95000,
    "ar": 28000,
    "ap": 19000,
    "cash": 98000,
    "monthly_burn": 14200,         # cash_runway = 98000/14200 ~= 6.9
    "retail_revenue": 42300,       # retail_pct = 42300/187500 = 22.56%
    "cogs": 75000,
    "days_in_month": 30,
    "trend_6mo": [
        {"gross_margin": 55.2, "net_margin": 6.1, "revenue_mom": 1.2},
        {"gross_margin": 57.0, "net_margin": 7.3, "revenue_mom": 2.1},
        {"gross_margin": 58.5, "net_margin": 8.0, "revenue_mom": 3.4},
        {"gross_margin": 59.1, "net_margin": 8.5, "revenue_mom": 2.8},
        {"gross_margin": 59.8, "net_margin": 8.9, "revenue_mom": 4.1},
    ]
}

(qbo_fixture_dir / "2026-04.json").write_text(json.dumps(fixture_data, indent=2))

# ── SKILL.md (the reference document) ───────────────────────────────────────
skill_md = Path("skills/client-dashboard/SKILL.md")
(workspace / skill_md).write_text("""\
---
name: client-dashboard
description: >
  Generates a client-facing executive KPI dashboard from QuickBooks Online data. Produces an
  Excel workbook with traffic-light scoring, 6-month trend sparklines, client-specific watch
  items, and a CDC log tracking KPI changes month-over-month. Use after monthly close to
  deliver the final executive summary deliverable to clients.
version: 1.0.0
tags:
  - finance
  - accounting
  - dashboard
  - KPI
  - client-reporting
  - QBO
updated: 2026-03-18
---

# Client Dashboard / KPI Report — SKILL.md

## What This Skill Does

Generates a client-facing executive KPI dashboard from QuickBooks Online data. Produces an Excel workbook with traffic-light scoring, 6-month trend sparklines, client-specific watch items, and a CDC log tracking KPI changes month-over-month.

## When To Use

- Monthly close is complete and it's time to generate the client dashboard
- User asks for KPI report, dashboard, or executive summary for any client
- After running P&L Quick Compare and bank rec — this is the final deliverable step

## When NOT To Use

- NOT a substitute for P&L Quick Compare (different purpose — this is executive summary, not variance analysis)
- NOT for mid-month snapshots — designed for complete monthly periods
- NOT for YTD / annual reports — use P&L Deep Analysis for those
- NOT for clients without QBO integration (no data source)

---

## Pipeline: `scripts/pipelines/client-dashboard.py`

### Prerequisites
```bash
pip install openpyxl
# Node.js qbo-client must be authenticated for the target slug
```

### Usage

```bash
# Example — March 2026
python3 scripts/pipelines/client-dashboard.py --slug <client-slug> --month 2026-03

# Custom output directory
python3 scripts/pipelines/client-dashboard.py --slug <client-slug> --month 2026-03 --out ~/Desktop/reports

# QBO sandbox
python3 scripts/pipelines/client-dashboard.py --slug <client-slug> --month 2026-03 --sandbox
```

### Arguments

| Argument | Required | Description |
|----------|----------|-------------|
| `--slug` | ✅ | Company slug (must match qbo-client connection) |
| `--month` | ✅ | Report month: `YYYY-MM` format |
| `--out` | ❌ | Output directory (default: `~/Desktop`) |
| `--sandbox` | ❌ | Use QBO sandbox environment |

---

## Output: Excel Workbook

**Filename:** `KPI_Dashboard_{slug}_{YYYY_MM}.xlsx`

| Tab | Contents |
|-----|----------|
| **Executive Summary** | Headline numbers + traffic-light KPI table with benchmarks |
| **KPI Scorecard** | Full KPI detail with definitions, thresholds, and score |
| **Trends** | 6-month KPI trend with sparklines (↑↗→↘↓ + block chars) |
| **Cash Position** | Balance sheet cash, CF summary, liquidity ratios, runway |
| **Watch Items** | SOP-driven priority items surfaced prominently |
| **CDC Log** | Month-over-month KPI delta (what changed since last run) |

---

## KPIs Computed

| KPI | Formula | Unit |
|-----|---------|------|
| Revenue MoM Growth | `(curr_rev - prior_rev) / prior_rev × 100` | % |
| Revenue YoY Growth | `(curr_rev - yoy_rev) / yoy_rev × 100` | % |
| Gross Margin % | `gross_profit / revenue × 100` | % |
| Gross Margin (3-Mo Avg) | Rolling 3-month GP/Revenue | % |
| Net Margin % | `net_income / revenue × 100` | % |
| OpEx Ratio | `total_opex / revenue × 100` | % |
| Interest Expense Ratio | `interest_expense / revenue × 100` | % |
| Current Ratio | `current_assets / current_liabilities` | x |
| Quick Ratio | `(current_assets - inventory) / current_liabilities` | x |
| Debt-to-Equity | `total_liabilities / total_equity` | x |
| DSO | `ar / (revenue / days)` | days |
| DPO | `ap / (cogs / days)` | days |
| Cash Runway | `cash / monthly_burn` | months |
| Retail % of Revenue | `retail_revenue / total_revenue × 100` | % |

**All math uses Python `Decimal` for precision.**

---

## Traffic Light Scoring

Each KPI is scored GREEN / YELLOW / RED based on configurable thresholds per client SOP.

```
🟢 GREEN  = On target (within green band)
🟡 WATCH  = Approaching threshold (yellow band)
🔴 ACTION = Below/above acceptable range (outside yellow band)
⬜ N/A    = KPI not applicable or not configured
```

Thresholds are defined in `CLIENT_CONFIGS` in the script — one config block per client slug.

---

## Client SOP Integration

### Adding a New Client
Add a block to `CLIENT_CONFIGS` in the script:
```python
"new-slug": {
    "company_name": "Company Name",
    "industry": "Industry",
    "has_ar": True,
    "has_headcount": False,
    "kpis_enabled": ["revenue_mom", "gross_margin", ...],
    "thresholds": {
        "gross_margin": {"green": (Decimal("45"), None), "yellow": (Decimal("35"), Decimal("45"))},
        ...
    },
    "watch_items": [...],
    "benchmarks": {...},
    "benchmark_source": "Source description",
}
```

---

## CDC (Change Data Capture)

Cache stored at: `.cache/client-dashboard/{slug}.json`

- First run: saves full KPI snapshot, CDC tab shows "First run" message
- Subsequent runs: diffs current KPIs vs. prior run
- CDC log shows: KPI label | Prior | Current | Delta | % Change | Improved/Declined

---

## Trend Sparklines

6-month trend for each KPI uses two formats:
1. **Direction arrows:** `↑↑ ↑ ↗ → ↘ ↓ ↓↓` (based on % change over period)
2. **Block bars:** `█▇▅▃▁_` (relative to max value — in Trends tab mini-chart section)

---

## Peer Benchmarks

Manual config only. Benchmark values live in `CLIENT_CONFIGS[slug]["benchmarks"]`.
Source attribution displayed in every tab footer.
To update: edit `benchmarks` dict and `benchmark_source` string per client.

---

## Integration with Pipeline Suite

This pipeline is designed to run **after** monthly close is complete:

```
1. Bank Reconciliation      (bank-reconciliation.py)
2. P&L Quick Compare        (pl-quick-compare.py)
3. P&L Deep Analysis        (pl-deep-analysis.py)      ← optional for controller level
4. Client Dashboard         (client-dashboard.py)      ← this script
5. Cash Flow Forecast       (cash-flow-forecast.py)    ← quarterly advisory
```

---

## File Locations

| File | Path |
|------|------|
| Pipeline script | `scripts/pipelines/client-dashboard.py` |
| Skill file | `skills/client-dashboard/SKILL.md` |
| CDC cache | `.cache/client-dashboard/{slug}.json` |
| Output (default) | `~/Desktop/KPI_Dashboard_{slug}_{YYYY_MM}.xlsx` |

---

## Troubleshooting

**QBO CLI error:** Ensure your QBO integration is authenticated for the slug.

**Missing KPIs:** If Balance Sheet accounts don't match expected labels, values default to 0. Check `extract_bs_metrics()` candidates list for account name variants.

**New client config:** Add slug to `CLIENT_CONFIGS` before first run. Default config uses generic thresholds (not client-specific).

**Decimal errors:** All financial math uses Python `Decimal`. Do not mix `float` — use `to_d()` helper for any external values.
""")

print("Workspace generated successfully.")
print(f"Key files:")
print(f"  scripts/pipelines/client-dashboard.py  (pipeline — needs ember-oak in CLIENT_CONFIGS)")
print(f"  .cache/qbo-fixtures/ember-oak/2026-04.json  (QBO fixture data)")
print(f"  skills/client-dashboard/SKILL.md  (reference documentation)")