import os
import json
import random

random.seed(42)

workspace = "/workspace"

# ── Distractor files simulating a messy legacy repo ──────────────────────────

# Old/wrong structure distractors
distractors = {
    "legacy/frontend/package.json": json.dumps({
        "name": "legacy-frontend",
        "version": "1.0.0",
        "dependencies": {"react": "17.0.2"}
    }, indent=2),

    "legacy/backend/index.js": "// old backend entry\nconsole.log('legacy');",

    "old-workspace.json": json.dumps({
        "packages": ["src/*", "lib/*"]
    }, indent=2),

    # Wrong turborepo config (uses old 'pipeline' key and wrong format)
    "turbo.old.json": json.dumps({
        "pipeline": {
            "build": {"dependsOn": ["^build"], "outputs": ["build/**"]},
            "test": {}
        }
    }, indent=2),

    # Misleading npm workspaces config
    "package-old.json": json.dumps({
        "name": "medplatform-old",
        "workspaces": ["packages/*", "apps/*"]
    }, indent=2),

    # Stray config files
    ".eslintrc.js": "module.exports = { extends: ['eslint:recommended'] };",
    "tsconfig.old.json": json.dumps({"compilerOptions": {"strict": False}}, indent=2),

    # Distractor markdown and logs
    "MIGRATION_NOTES.md": "# Migration\nWe are moving from lerna to a modern monorepo setup.\n",
    "build.log": "[ERROR] Cannot find module '@medplatform/ui'\n[ERROR] Cannot find module '@medplatform/utils'\n",
    "scripts/deploy.sh": "#!/bin/bash\necho 'deploy placeholder'\n",

    # Distractor sub-package with wrong naming convention
    "packages/shared/package.json": json.dumps({
        "name": "shared",
        "version": "0.0.1",
        "main": "index.js"
    }, indent=2),
    "packages/shared/index.js": "module.exports = {};",

    # Wrong workspace yaml (uses wrong glob)
    "pnpm-workspace.old.yaml": "packages:\n  - 'src/*'\n  - 'lib/*'\n",

    # Stray lockfile reference
    "yarn.lock": "# THIS FILE IS AUTOMATICALLY GENERATED\n",

    # App skeletons that are incomplete and wrongly named
    "apps/patient-portal/index.tsx": "export default function App() { return <div>Patient Portal</div>; }",
    "apps/patient-portal/package.json": json.dumps({
        "name": "patient-portal",
        "version": "0.1.0",
        "scripts": {"dev": "next dev"},
        "dependencies": {
            "react": "^18.0.0",
            "@medplatform/ui": "^1.0.0"
        }
    }, indent=2),

    "apps/admin-dashboard/index.tsx": "export default function Admin() { return <div>Admin</div>; }",
    "apps/admin-dashboard/package.json": json.dumps({
        "name": "admin-dashboard",
        "version": "0.1.0",
        "scripts": {"dev": "next dev"},
        "dependencies": {
            "react": "^18.0.0",
            "@medplatform/ui": "^0.9.0"
        }
    }, indent=2),

    # Incomplete root package.json (no workspace config, wrong scripts)
    "package.json": json.dumps({
        "name": "medplatform",
        "version": "0.0.1",
        "private": True,
        "scripts": {
            "build": "echo 'TODO: set up proper build'",
            "lint": "echo 'TODO'"
        },
        "devDependencies": {
            "typescript": "^5.0.0"
        }
    }, indent=2),
}

for rel_path, content in distractors.items():
    full_path = os.path.join(workspace, rel_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w") as f:
        f.write(content)

# Create a REQUIREMENTS file (business brief) for the agent
requirements = """\
MEDPLATFORM MONOREPO SETUP REQUIREMENTS
========================================

We are building a healthcare SaaS platform called "medplatform" under the @medplatform scope.

The platform consists of:

APPLICATIONS (in apps/):
  1. web          — Main patient-facing portal (Next.js)
  2. admin        — Internal admin dashboard (Next.js)

SHARED PACKAGES (in packages/):
  1. ui           — Shared React UI component library
                    → Used by BOTH web and admin apps
  2. utils        — Shared utility functions
                    → Used by BOTH web and admin apps
  3. config-eslint       — Shared ESLint configuration
                    → Used by ALL apps and packages
  4. config-typescript   — Shared TypeScript configuration
                    → Used by ALL apps and packages

DEPENDENCY WIRING:
  - apps/web depends on: @medplatform/ui, @medplatform/utils
  - apps/admin depends on: @medplatform/ui, @medplatform/utils
  - packages/ui depends on: @medplatform/config-eslint, @medplatform/config-typescript
  - packages/utils depends on: @medplatform/config-eslint, @medplatform/config-typescript

TASK PIPELINE:
  - build: must respect dependency order; cache outputs at dist/** and .next/**
  - lint: must run after dependencies are built
  - test: must run after dependencies are built

TOOLING:
  - Use pnpm workspaces + Turborepo
  - Package manager config file: pnpm-workspace.yaml
  - Turborepo config file: turbo.json
  - Root package.json must wire the workspace and have turbo as devDependency

NOTE: The existing files in apps/ and packages/ are legacy/incomplete and need to be replaced
or supplemented with the correct setup. The naming convention for internal packages must be consistent.
"""

with open(os.path.join(workspace, "REQUIREMENTS.txt"), "w") as f:
    f.write(requirements)

print("Workspace generated successfully.")
print("Files created:")
for rel_path in sorted(distractors.keys()):
    print(f"  {rel_path}")