from pathlib import Path
import json

# Deterministic marker file for the task harness
payload = {
    "marker": "LLMFIT_ADVISOR_HARD_TASK_V1",
    "notes": [
        "system and recommendation outputs should be generated by the assistant",
        "eval will look for exact output filenames and validate JSON structure",
    ],
}
Path("task_marker.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")
