import os
import random
import textwrap

random.seed(42)

# Create the project directory structure (genomics ETL pipeline)
dirs = [
    "src/ingestion",
    "src/transforms",
    "src/validation",
    "src/config",
    "src/generated",
    "src/stores",
    "tests/unit",
    "tests/integration",
    "tests/fixtures",
    "agent_docs",
    "scripts",
    "data/raw",
    "data/processed",
    ".github",
]
for d in dirs:
    os.makedirs(d, exist_ok=True)

# --- Distractor files ---
distractor_files = {
    "src/ingestion/vcf_parser.py": textwrap.dedent("""\
        # VCF file parser for genomics pipeline
        from typing import Iterator, Dict, Any
        
        def parse_vcf(filepath: str) -> Iterator[Dict[str, Any]]:
            with open(filepath) as f:
                for line in f:
                    if line.startswith('#'):
                        continue
                    parts = line.strip().split('\\t')
                    yield {
                        'chrom': parts[0],
                        'pos': int(parts[1]),
                        'ref': parts[3],
                        'alt': parts[4],
                    }
    """),
    "src/ingestion/fastq_reader.py": textwrap.dedent("""\
        # FASTQ reader
        def read_fastq(filepath):
            with open(filepath) as f:
                while True:
                    header = f.readline().strip()
                    if not header:
                        break
                    seq = f.readline().strip()
                    f.readline()  # +
                    qual = f.readline().strip()
                    yield header, seq, qual
    """),
    "src/transforms/normalize.py": textwrap.dedent("""\
        # Normalization transforms
        def normalize_chrom(chrom: str) -> str:
            if not chrom.startswith('chr'):
                return f'chr{chrom}'
            return chrom
    """),
    "src/transforms/filter_variants.py": textwrap.dedent("""\
        # Filter variants by quality score
        def filter_by_qual(variants, min_qual=30):
            return [v for v in variants if v.get('qual', 0) >= min_qual]
    """),
    "src/validation/schema.py": textwrap.dedent("""\
        # Schema validation for genomic records
        REQUIRED_FIELDS = ['chrom', 'pos', 'ref', 'alt']
        
        def validate_record(record: dict) -> bool:
            return all(field in record for field in REQUIRED_FIELDS)
    """),
    "src/config/settings.py": textwrap.dedent("""\
        # Configuration - always import from here, never read env directly
        import os
        
        GENOME_REFERENCE = os.environ.get('GENOME_REF', 'hg38')
        DB_URL = os.environ.get('DATABASE_URL', 'postgresql://localhost/genomics')
        BATCH_SIZE = int(os.environ.get('BATCH_SIZE', '1000'))
    """),
    "src/generated/prisma_client.py": textwrap.dedent("""\
        # AUTO-GENERATED by Prisma - DO NOT MODIFY
        # Generated at: 2025-01-15T10:00:00Z
        class PrismaClient:
            pass
    """),
    "src/stores/variant_cache.py": textwrap.dedent("""\
        # Variant cache store (Zustand-style state management)
        class VariantCache:
            def __init__(self):
                self._cache = {}
            
            def get(self, key):
                return self._cache.get(key)
            
            def set(self, key, value):
                self._cache[key] = value
    """),
    "tests/unit/test_normalize.py": textwrap.dedent("""\
        import pytest
        from src.transforms.normalize import normalize_chrom
        
        def test_normalize_adds_chr_prefix():
            assert normalize_chrom('1') == 'chr1'
        
        def test_normalize_idempotent():
            assert normalize_chrom('chr1') == 'chr1'
    """),
    "tests/integration/test_pipeline.py": textwrap.dedent("""\
        # Integration tests require DB up: docker compose up db first
        import pytest
        
        @pytest.mark.integration
        def test_full_pipeline():
            pass
    """),
    "tests/fixtures/sample.vcf": textwrap.dedent("""\
        ##fileformat=VCFv4.2
        #CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO
        chr1\t925952\t.\tG\tA\t50\tPASS\t.
        chr2\t38298145\t.\tC\tT\t45\tPASS\t.
    """),
    "agent_docs/conventions.md": textwrap.dedent("""\
        # Conventions
        
        ## Naming
        - Modules: snake_case
        - Classes: PascalCase
        - Constants: UPPER_SNAKE_CASE
        
        ## File structure
        - One class per file for domain objects
        - Utility functions grouped by domain
        
        ## Error handling
        - Use Result types from src/lib/errors.py
        - Never use bare try/except
    """),
    "agent_docs/architecture.md": textwrap.dedent("""\
        # Architecture
        
        ## Data Flow
        Raw VCF/FASTQ → Ingestion → Normalization → Validation → DB Write
        
        ## Key Decisions
        - PostgreSQL for variant storage (ACID guarantees)
        - Batch processing with configurable batch size
        - All config through src/config/settings.py
    """),
    "agent_docs/gotchas.md": textwrap.dedent("""\
        # Extended Gotchas
        
        ## VCF Chromosome Names
        External VCFs often omit 'chr' prefix. Always normalize before DB write.
        The normalize_chrom function handles this but callers forget to call it.
        
        ## Integration Test Database
        Integration tests will silently pass (vacuous truth) if DB is not up.
        Always run: docker compose up db && pytest tests/integration/
        
        ## Batch Size Memory
        Large batch sizes (>10000) cause OOM on standard EC2 instances.
        Default 1000 is safe. Document any change in PR.
    """),
    "data/raw/.gitkeep": "",
    "data/processed/.gitkeep": "",
    ".github/CODEOWNERS": "* @genomics-team\n",
}

for filepath, content in distractor_files.items():
    with open(filepath, 'w') as f:
        f.write(content)

# --- Scripts directory: the init script exists but has not been run ---
# The skill says "All scripts mentioned in the SKILL.md already exist in the workspace"
# So we create stub scripts that exist but do nothing harmful
scripts = {
    "scripts/init-agent-context.sh": textwrap.dedent("""\
        #!/usr/bin/env bash
        # init-agent-context.sh - stub (task requires manual setup)
        echo "init-agent-context.sh: not run automatically in this environment"
    """),
    "scripts/compress.sh": textwrap.dedent("""\
        #!/usr/bin/env bash
        echo "compress.sh: not yet implemented"
    """),
    "scripts/promote.sh": textwrap.dedent("""\
        #!/usr/bin/env bash
        echo "promote.sh: not yet implemented"
    """),
    "scripts/validate.sh": textwrap.dedent("""\
        #!/usr/bin/env bash
        echo "validate.sh: not yet implemented"
    """),
    "scripts/publish-template.sh": textwrap.dedent("""\
        #!/usr/bin/env bash
        echo "publish-template.sh: not yet implemented"
    """),
    "scripts/agents-local-template.md": textwrap.dedent("""\
        # .agents.local.md (template)
        
        ## Preferences
        
        ## Patterns
        
        ## Gotchas
        
        ## Dead Ends
        
        ## Ready to Promote
        
        ## Session Log
        
        ## Compression Log
    """),
}

for filepath, content in scripts.items():
    with open(filepath, 'w') as f:
        f.write(content)
    os.chmod(filepath, 0o755)

# --- Git initialization (no .gitignore yet - agent must create/update it) ---
os.system("git init -b main 2>/dev/null || git init 2>/dev/null")
os.system("git config user.email 'agent@test.local'")
os.system("git config user.name 'Agent Test'")

# Existing .gitignore that does NOT include .agents.local.md
gitignore_content = textwrap.dedent("""\
    __pycache__/
    *.pyc
    *.pyo
    .env
    data/raw/*.vcf
    data/processed/*.parquet
    .DS_Store
    *.egg-info/
    dist/
    build/
    .pytest_cache/
""")
with open(".gitignore", "w") as f:
    f.write(gitignore_content)

# Stage existing files (but NOT agents files - agent must create those)
os.system("git add -A 2>/dev/null")
os.system("git commit -m 'initial project scaffold' 2>/dev/null")

# --- Session history data for the agent to use ---
# This simulates accumulated session notes that the agent must analyze
# to determine what needs to go into Ready to Promote (3+ sessions pattern)
session_history_note = textwrap.dedent("""\
    # SESSION HISTORY NOTES (internal reference - not a project file)
    # These are raw notes from the last 4 working sessions on this project.
    # The agent context system setup task should use these to populate the scratchpad.
    
    ## Session 2025-01-10
    - Worked on VCF ingestion
    - Discovered: always call normalize_chrom before any DB write or comparison
    - Integration tests failed because DB was not up (docker compose up db needed)
    - normalize_chrom pattern confirmed working
    
    ## Session 2025-01-13
    - Refactored filter_variants, added quality threshold config
    - AGAIN forgot to run normalize_chrom on new code path - caught in review
    - Decided: Result types in src/lib/errors.py, not try/catch blocks
    - normalize_chrom must be called on all chrom values before processing
    
    ## Session 2025-01-14
    - Added validation schema, integrated with pipeline
    - normalize_chrom omission caused a subtle bug in chr-prefix comparison
    - Fixed by making it a pipeline step, not caller responsibility
    - Config always through src/config/settings.py confirmed as team standard
    
    ## Session 2025-01-15 (current)
    - Setting up agent context system for the team
    - normalize_chrom recurrence across 3+ sessions - should be promoted
    - Integration tests silently pass without DB up - recurring gotcha
""")

with open("SESSION_HISTORY_NOTES.txt", "w") as f:
    f.write(session_history_note)

print("Workspace generated successfully.")
print(f"Files created: {len(distractor_files) + len(scripts) + 3} files")