import json
import random
import os
from pathlib import Path

random.seed(42)

workspace = Path("/workspace")
workspace.mkdir(exist_ok=True)

# ── 1. Realistic distractor directory structure ──────────────────────────────
dirs = [
    "ops/legacy_logs",
    "ops/archive/2024",
    "ops/archive/2025",
    "infra/configs",
    "infra/monitoring",
    "pipeline/schemas",
    "pipeline/tests",
    "reports/old",
    "reports/drafts",
    "docs",
]
for d in dirs:
    (workspace / d).mkdir(parents=True, exist_ok=True)

# Distractor files — realistic but unrelated
distractors = {
    "ops/legacy_logs/agent_comm_2024_q3.csv": (
        "from,to,count,avg_latency\n"
        "order-intake,inventory-check,1200,32\n"
        "inventory-check,payment-proc,980,67\n"
        "payment-proc,shipping-coord,870,55\n"
    ),
    "ops/legacy_logs/raw_dump.txt": (
        "RAW DUMP - DO NOT USE\n"
        "2024-11-01 agent-a -> agent-b 120ms\n"
        "2024-11-01 agent-b -> agent-c 340ms\n"
    ),
    "ops/archive/2024/summary.json": json.dumps({
        "period": "2024",
        "total_messages": 45000,
        "avg_latency_ms": 62,
        "notes": "Legacy format, not compatible with new analyzer"
    }, indent=2),
    "ops/archive/2025/q1_notes.md": (
        "# Q1 2025 Agent Communication Notes\n\n"
        "- High latency observed in payment processing cluster\n"
        "- inventory-check agent showing signs of overload\n"
        "- Recommended: Add caching layer\n"
    ),
    "infra/configs/network_topology.yaml": (
        "agents:\n"
        "  - name: order-intake\n    replicas: 2\n"
        "  - name: inventory-check\n    replicas: 1\n"
        "  - name: payment-proc\n    replicas: 1\n"
        "  - name: shipping-coord\n    replicas: 3\n"
        "  - name: fraud-detector\n    replicas: 1\n"
        "  - name: notifier\n    replicas: 2\n"
    ),
    "infra/monitoring/alerts.json": json.dumps([
        {"alert": "high_latency", "agent": "payment-proc", "threshold_ms": 200, "active": True},
        {"alert": "queue_depth", "agent": "inventory-check", "threshold": 500, "active": True},
    ], indent=2),
    "pipeline/schemas/message_schema_v1.json": json.dumps({
        "version": "1",
        "fields": ["source", "dest", "ts", "msg_type", "size_bytes", "duration_ms", "result"],
        "note": "DEPRECATED - v1 schema used before 2025"
    }, indent=2),
    "pipeline/schemas/message_schema_v2.json": json.dumps({
        "version": "2",
        "fields": ["id", "sender", "receiver", "time", "kind", "bytes", "latency", "outcome"],
        "note": "Internal draft schema - not finalized"
    }, indent=2),
    "pipeline/tests/test_harness.sh": (
        "#!/bin/bash\n"
        "# Placeholder test harness\n"
        "echo 'Running pipeline integration tests...'\n"
        "exit 0\n"
    ),
    "reports/old/bottleneck_report_2024.txt": (
        "Bottleneck Analysis - 2024 Q4\n"
        "================================\n"
        "Primary bottleneck: payment-proc (avg 310ms)\n"
        "Secondary: inventory-check (avg 180ms)\n"
        "Recommendation: scale horizontally\n"
    ),
    "reports/drafts/comm_analysis_draft.json": json.dumps({
        "status": "draft",
        "warning": "This is a manually compiled draft — not generated by analyzer",
        "data": {}
    }, indent=2),
    "docs/pipeline_overview.md": (
        "# Order Processing Pipeline\n\n"
        "The logistics platform uses multiple AI agents:\n"
        "- **order-intake**: Receives customer orders\n"
        "- **inventory-check**: Verifies stock availability\n"
        "- **fraud-detector**: Screens for fraudulent orders\n"
        "- **payment-proc**: Processes payments\n"
        "- **shipping-coord**: Arranges delivery\n"
        "- **notifier**: Sends customer notifications\n\n"
        "Known issues: payment-proc shows high latency under load.\n"
    ),
}

for path, content in distractors.items():
    (workspace / path).write_text(content)

# ── 2. Generate the realistic (messy) agent communication log ─────────────
agents = [
    "order-intake",
    "inventory-check",
    "fraud-detector",
    "payment-proc",
    "shipping-coord",
    "notifier",
]

# Define traffic patterns with intentional bottleneck at payment-proc
traffic_patterns = [
    ("order-intake",     "inventory-check",  "request",   512,   38),
    ("inventory-check",  "fraud-detector",   "request",   256,   55),
    ("fraud-detector",   "payment-proc",     "request",   768,  320),  # bottleneck
    ("payment-proc",     "shipping-coord",   "request",   1024, 310),  # bottleneck
    ("shipping-coord",   "notifier",         "request",   128,   22),
    ("order-intake",     "fraud-detector",   "request",   384,   48),
    ("inventory-check",  "payment-proc",     "request",   512,  295),  # bottleneck
    ("payment-proc",     "notifier",         "response",  256,  305),  # bottleneck
    ("fraud-detector",   "notifier",         "event",     128,   18),
    ("notifier",         "order-intake",     "response",  64,    12),
    ("shipping-coord",   "inventory-check",  "request",   256,   41),
    ("order-intake",     "shipping-coord",   "event",     192,   35),
]

statuses = ["delivered", "delivered", "delivered", "delivered", "timeout", "delivered"]

messages = []
base_ts = "2026-03-10T08:00:00Z"

from datetime import datetime, timedelta

base_dt = datetime(2026, 3, 10, 8, 0, 0)
msg_id = 1

for i in range(200):
    pattern = random.choice(traffic_patterns)
    frm, to, msg_type, base_size, base_latency = pattern
    
    # Add realistic noise
    payload_size = base_size + random.randint(-64, 128)
    latency_ms = base_latency + random.randint(-15, 40)
    if latency_ms < 1:
        latency_ms = 1
    
    # Occasional failures on high-latency paths
    if base_latency > 280 and random.random() < 0.15:
        status = "timeout"
    elif random.random() < 0.03:
        status = "error"
    else:
        status = "delivered"
    
    ts = base_dt + timedelta(seconds=i * 18 + random.randint(0, 15))
    timestamp = ts.strftime("%Y-%m-%dT%H:%M:%SZ")
    
    messages.append({
        "id": f"msg-{msg_id:04d}",
        "from": frm,
        "to": to,
        "timestamp": timestamp,
        "type": msg_type,
        "payload_size": max(64, payload_size),
        "latency_ms": latency_ms,
        "status": status
    })
    msg_id += 1

# Shuffle to make it non-trivially ordered
random.shuffle(messages)

log_file = workspace / "ops" / "order_pipeline_comms_2026_03.json"
log_file.write_text(json.dumps(messages, indent=2))

print(f"Generated {len(messages)} messages in {log_file}")
print("Workspace structure created with distractor files.")
print("Task: Agent must use the traffic analyzer tool to produce a full report.")