import os
import json
import textwrap
from pathlib import Path

BASE = Path("/home/ubuntu/.openclaw/workspace")

# ── reference files (the skill's own documentation) ──────────────────────────
refs = BASE / "goal-mode" / "references"
refs.mkdir(parents=True, exist_ok=True)

# schemas.md
(refs / "schemas.md").write_text(textwrap.dedent("""
# Shared Schemas

## session.json
```json
{
  "goal_id": "string  (uuid-like, generated by agent)",
  "goal_text": "string",
  "goal_slug": "string",
  "status": "active | finished",
  "created_at": "ISO 8601",
  "updated_at": "ISO 8601",
  "criteria": [
    {
      "id": "string",
      "text": "string  (under 120 chars, narrow/specific)",
      "covered": false,
      "best_relevance": 0.0
    }
  ],
  "pages": [
    {
      "url": "string",
      "title": "string",
      "evaluated_at": "ISO 8601",
      "relevance_score": 0.0,
      "findings": []
    }
  ],
  "candidates": []
}
```

## criteria.json
Snapshot of the criteria array from session.json. Written every time criteria change.
```json
[
  {
    "id": "string",
    "text": "string",
    "covered": false,
    "best_relevance": 0.0
  }
]
```

## active-session.md
Markdown status file updated on EVERY operation.
Must include:
- Goal text
- Status (active/finished)
- Coverage summary: X/N criteria covered
- Last operation performed
- Timestamp of last update

## active-goal.json
```json
{
  "goal_slug": "string",
  "goal_text": "string",
  "session_path": "absolute path to session.json"
}
```
""").strip())

# generate-criteria.md
(refs / "generate-criteria.md").write_text(textwrap.dedent("""
# generate_criteria

Generate a new research goal with evaluation criteria.

## Required input fields
- `goal_text` (string): The user's research goal

## Optional input fields
- `context` (string): Additional context about the goal
- `num_criteria` (integer, default 6): Number of criteria to generate (min 4, max 12)

## Output schema
```json
{
  "operation": "generate_criteria",
  "goal_id": "string",
  "goal_slug": "string",
  "goal_text": "string",
  "criteria": [
    {
      "id": "c1",
      "text": "string (narrow, specific, under 120 chars)",
      "covered": false,
      "best_relevance": 0.0
    }
  ]
}
```

## Criteria quality rules
- Each criterion MUST be narrow enough that a single overview page cannot satisfy more than 2-3.
- Bad: "Storage capacity"
- Good: "Storage capacity: maximum raw TB supported across all drive bays"
- Bad: "Performance"
- Good: "Sequential read/write throughput in MB/s under RAID-5 with 4 drives"
- Bad: "Software features"
- Good: "Docker/container runtime support: native package manager or community plugin"

## Persist
1. Write `{baseDir}/goal-mode/{goal_slug}/session.json` — full session object (status: "active")
2. Write `{baseDir}/goal-mode/{goal_slug}/criteria.json` — criteria array snapshot
3. Write `{baseDir}/goal-mode/active-goal.json` — pointer to this goal
4. Write `{baseDir}/memory/goal-mode/active-session.md` — live status markdown
""").strip())

# evaluate-page.md
(refs / "evaluate-page.md").write_text(textwrap.dedent("""
# evaluate_page

Evaluate a visited web page against the active goal's criteria.

## Required input fields
- `goal_slug` (string): Identifies the active session
- `url` (string): URL of the page
- `title` (string): Page title
- `content_summary` (string): Text content / summary of the page
- `criteria` (array): Current criteria array from session.json (with id, text, covered, best_relevance)

## Output schema
```json
{
  "operation": "evaluate_page",
  "url": "string",
  "title": "string",
  "relevance_score": 0.0,
  "findings": [
    {
      "type": "string  (dynamically chosen based on goal context, NOT shopping defaults)",
      "text": "string (under 240 chars)",
      "confidence": 0.0
    }
  ],
  "criteria_relevance": [
    {
      "criterion": "exact criterion text string",
      "relevance": 0.0,
      "covered": false
    }
  ],
  "recommendation": "string | null"
}
```

## Scoring rules
- `relevance_score`: overall page relevance to the goal, 0.0–1.0
- `criteria_relevance` MUST contain one entry for EVERY criterion in the input `criteria` array.
- `criterion` values MUST be exact strings from the input — do NOT rephrase.
- A criterion is only `covered: true` when `relevance >= 0.7` AND the depth-over-breadth rule is met.
- **Depth-over-breadth:** A listicle, roundup, or overview page that mentions a topic in one paragraph scores 0.3–0.5. Reserve 0.7+ for dedicated, detailed coverage.
- **Per-page coverage cap:** A single page can flip at most 3 criteria from uncovered→covered. If more than 3 criteria would cross the 0.7 threshold, only the top 3 by relevance score are marked `covered: true`; the rest keep their updated `relevance` value but `covered: false` until confirmed by another page.
- All `confidence` values are floats 0.0–1.0. Never use string enums.
- Findings must be dynamically typed to the goal domain (e.g., for NAS research: "throughput_data", "compatibility_note", "software_feature", "hardware_spec" — NOT "price_drop" or "deal_alert").
- `recommendation`: short actionable suggestion, or `null` if evidence is insufficient.

## Persist
1. Read `{baseDir}/goal-mode/{goal_slug}/session.json`
2. Append this page evaluation to `session.json` → `pages` array; update `criteria[].covered` and `criteria[].best_relevance` where improved; update `updated_at`
3. Write updated `session.json`
4. Write `{baseDir}/goal-mode/{goal_slug}/criteria.json` — updated criteria snapshot
5. Write event file: `{baseDir}/goal-mode/{goal_slug}/events/{timestamp}-evaluate-page.json`
   - timestamp format: ISO 8601 compact: `YYYYMMDDTHHmmssZ`  (e.g., `20240315T143022Z`)
   - Event file content: the full evaluate_page output JSON
6. Write `{baseDir}/memory/goal-mode/active-session.md` — updated live status
""").strip())

# update-criteria.md
(refs / "update-criteria.md").write_text(textwrap.dedent("""
# update_criteria

Add, remove, or modify criteria for an active goal.

## Required input fields
- `goal_slug` (string)
- `updates` (array of update objects)

## Update object schema
```json
{
  "action": "add | remove | modify",
  "criterion_id": "string  (required for remove/modify)",
  "text": "string  (required for add/modify)"
}
```

## Output schema
```json
{
  "operation": "update_criteria",
  "goal_slug": "string",
  "criteria": [ { "id": "...", "text": "...", "covered": false, "best_relevance": 0.0 } ]
}
```

## Persist
1. Read and update `{baseDir}/goal-mode/{goal_slug}/session.json`
2. Write updated `session.json`
3. Write `{baseDir}/goal-mode/{goal_slug}/criteria.json`
4. Write `{baseDir}/memory/goal-mode/active-session.md`
""").strip())

# create-wrap-up.md
(refs / "create-wrap-up.md").write_text(textwrap.dedent("""
# create_wrap_up

Finish a research session and produce a comprehensive wrap-up.

## Required input fields
- `goal_slug` (string)

## Output schema
```json
{
  "operation": "create_wrap_up",
  "goal_slug": "string",
  "goal_text": "string",
  "summary": "string (concise overview of what was learned)",
  "criteria_coverage": {
    "total": 0,
    "covered": 0,
    "uncovered_criteria": ["string"]
  },
  "key_findings": [
    {
      "type": "string",
      "text": "string (under 240 chars)",
      "confidence": 0.0
    }
  ],
  "recommendation": "string | null",
  "pages_evaluated": 0,
  "status": "finished"
}
```

## Recommendation rule
`recommendation` MUST be `null` when:
- Fewer than 3 criteria are covered, OR
- Fewer than 2 pages have been evaluated, OR
- Evidence is contradictory or insufficient

## Persist
1. Read `{baseDir}/goal-mode/{goal_slug}/session.json`
2. Update `session.json`: set `status` to `"finished"`, update `updated_at`
3. Write updated `session.json`
4. Write `{baseDir}/goal-mode/{goal_slug}/wrap-up.json` — the wrap-up output
5. Write `{baseDir}/memory/goal-mode/latest-session.md` — human-readable summary of this session
6. Append to `{baseDir}/memory/goal-mode/history.md` — one-line log entry:
   `{ISO timestamp} | {goal_slug} | {pages_evaluated} pages | {covered}/{total} criteria covered`
7. Write `{baseDir}/memory/goal-mode/active-session.md` — mark as finished
""").strip())

# resume-goal.md
(refs / "resume-goal.md").write_text(textwrap.dedent("""
# resume_goal

Resume a previously active or finished goal session.

## Required input fields
- `goal_slug` (string)

## Output schema
```json
{
  "operation": "resume_goal",
  "goal_slug": "string",
  "goal_text": "string",
  "status": "active | finished",
  "criteria": [],
  "pages_evaluated": 0,
  "coverage_summary": "X/N criteria covered"
}
```

## Persist
1. Read `{baseDir}/goal-mode/{goal_slug}/session.json`
2. Write `{baseDir}/goal-mode/active-goal.json` — update pointer to this goal
3. Write `{baseDir}/memory/goal-mode/active-session.md` — updated live status
""").strip())

# ── distractors ──────────────────────────────────────────────────────────────
distractor_root = BASE / "goal-mode"

# Old stale session from a previous goal (do not confuse agent)
old_slug = "old-laptop-research-2023"
old_session_dir = distractor_root / old_slug
old_session_dir.mkdir(parents=True, exist_ok=True)
(old_session_dir / "session.json").write_text(json.dumps({
    "goal_id": "abc-111",
    "goal_text": "Find a good laptop for video editing",
    "goal_slug": old_slug,
    "status": "finished",
    "created_at": "2023-11-01T10:00:00Z",
    "updated_at": "2023-11-03T15:30:00Z",
    "criteria": [
        {"id": "c1", "text": "CPU: sustained multi-core performance under Cinebench R23", "covered": True, "best_relevance": 0.82},
        {"id": "c2", "text": "Display: color accuracy DCI-P3 coverage percentage", "covered": False, "best_relevance": 0.4}
    ],
    "pages": [],
    "candidates": []
}, indent=2))
(old_session_dir / "criteria.json").write_text(json.dumps([
    {"id": "c1", "text": "CPU: sustained multi-core performance under Cinebench R23", "covered": True, "best_relevance": 0.82}
], indent=2))
(old_session_dir / "wrap-up.json").write_text(json.dumps({
    "operation": "create_wrap_up",
    "goal_slug": old_slug,
    "status": "finished"
}, indent=2))

events_old = old_session_dir / "events"
events_old.mkdir(parents=True, exist_ok=True)
(events_old / "20231101T120000Z-evaluate-page.json").write_text(json.dumps({
    "operation": "evaluate_page",
    "url": "https://example.com/laptop-review",
    "relevance_score": 0.75
}, indent=2))

# Memory distractors
memory = BASE / "memory" / "goal-mode"
memory.mkdir(parents=True, exist_ok=True)
(memory / "history.md").write_text(
    "2023-11-03T15:30:00Z | old-laptop-research-2023 | 3 pages | 1/2 criteria covered\n"
)
(memory / "latest-session.md").write_text(textwrap.dedent("""
# Latest Session: old-laptop-research-2023
Goal: Find a good laptop for video editing
Status: finished
Pages evaluated: 3
Coverage: 1/2
""").strip())
(memory / "active-session.md").write_text(textwrap.dedent("""
# Active Session
Goal: Find a good laptop for video editing
Status: finished
Coverage: 1/2 criteria covered
Last operation: create_wrap_up
Updated: 2023-11-03T15:30:00Z
""").strip())

# Distractor config files to add noise
config_dir = BASE / "goal-mode" / "_config"
config_dir.mkdir(parents=True, exist_ok=True)
(config_dir / "defaults.json").write_text(json.dumps({
    "default_num_criteria": 6,
    "max_findings_per_page": 10,
    "slug_max_length": 60
}, indent=2))
(config_dir / "feature-flags.json").write_text(json.dumps({
    "enable_candidates": False,
    "enable_deep_crawl": False
}, indent=2))

# Distractor temp files
tmp_dir = BASE / "goal-mode" / "_tmp"
tmp_dir.mkdir(parents=True, exist_ok=True)
(tmp_dir / "scratch.txt").write_text("old scratch notes — ignore\n")
(tmp_dir / "broken-session.json").write_text('{"goal_id": "broken", "criteria":')  # intentionally broken JSON

# Distractor memory files
(BASE / "memory" / "goal-mode" / "notes.txt").write_text("informal notes — not part of schema\n")
(BASE / "memory" / "goal-mode" / "ARCHIVE.md").write_text("# Archive\nOld sessions archived here.\n")

# ── THE TASK INPUT FILE ───────────────────────────────────────────────────────
# This is what the agent must process: three chained operations in sequence
task_input = {
    "operations": [
        {
            "operation": "generate_criteria",
            "input": {
                "goal_text": "Select the best NAS device for a 4K home media server with Docker support",
                "context": "Budget under $600, 4-8 drive bays, needs to run Plex and containerized services",
                "num_criteria": 6
            }
        },
        {
            "operation": "evaluate_page",
            "input": {
                "url": "https://www.servethehome.com/best-nas-2024-overview/",
                "title": "Best NAS Devices of 2024: A Complete Overview",
                "content_summary": (
                    "This roundup article briefly covers 12 different NAS units. "
                    "It mentions that the Synology DS923+ has 4 bays and supports Docker via Container Manager, "
                    "noting it uses AMD Ryzen R1600 with 4GB ECC RAM. The QNAP TS-464 is listed as having "
                    "quad-core Celeron N5105 and native container support. Drive capacity is mentioned in passing: "
                    "'most units support up to 108TB raw with 18TB drives.' The article has a one-paragraph section "
                    "on each device. Sequential throughput figures are not provided — only 'good performance' is noted. "
                    "Noise levels get one sentence per device. Power consumption data is absent. "
                    "Price ranges are listed as '$300-$600 for prosumer units.' "
                    "Plex transcoding capability is mentioned for three devices in a single bullet point each. "
                    "The article does not benchmark any device; it aggregates manufacturer specs."
                )
            }
        },
        {
            "operation": "create_wrap_up",
            "input": {}
        }
    ]
}

task_file = BASE / "task_input.json"
task_file.write_text(json.dumps(task_input, indent=2))

print("Workspace generated successfully.")
print(f"Task input written to: {task_file}")