import os
import json
import random

random.seed(42)

WORKSPACE = "/workspace"

# ── directory skeleton ────────────────────────────────────────────────────────
dirs = [
    "skills/excalidraw-diagram-generator/scripts",
    "skills/excalidraw-diagram-generator/references",
    "skills/excalidraw-diagram-generator/templates",
    "skills/excalidraw-diagram-generator/libraries/payment-icons/icons",
    "docs/architecture",
    "docs/design",
    "src/payments",
    "src/api",
    "tests/unit",
    "tests/integration",
    "config",
]
for d in dirs:
    os.makedirs(os.path.join(WORKSPACE, d), exist_ok=True)

# ── distractor files ─────────────────────────────────────────────────────────
distractors = {
    "docs/architecture/old-sequence.md": "# Old Sequence\n(deprecated, see Confluence)\n",
    "docs/architecture/component-list.txt": "Client\nAPI Gateway\nPayment Processor\nDatabase\n",
    "docs/design/wireframes-notes.txt": "Use rectangles for services, arrows for messages.\n",
    "src/payments/checkout.py": "def process_payment(card, amount):\n    pass\n",
    "src/payments/refund.py": "def refund(txn_id):\n    pass\n",
    "src/api/routes.py": "# POST /checkout\n# POST /refund\n",
    "tests/unit/test_checkout.py": "def test_checkout(): assert True\n",
    "tests/integration/test_flow.py": "# integration tests\n",
    "config/app.yaml": "env: production\nlog_level: info\n",
    "config/secrets.example.env": "DB_PASSWORD=changeme\nAPI_KEY=changeme\n",
    ".gitignore": "*.pyc\n__pycache__/\n.env\n",
}
for rel, content in distractors.items():
    path = os.path.join(WORKSPACE, rel)
    with open(path, "w") as f:
        f.write(content)

# ── reference.md for payment-icons library ───────────────────────────────────
reference_md = """# Payment Icons Reference

| Icon Name | File | Description |
|-----------|------|-------------|
| credit-card | icons/credit-card.json | Credit card symbol |
| lock | icons/lock.json | Security / lock icon |
| database | icons/database.json | Database cylinder |
| server | icons/server.json | Server rack |
| gateway | icons/gateway.json | API gateway box |

Generated by split-excalidraw-library.py
"""
with open(os.path.join(WORKSPACE, "skills/excalidraw-diagram-generator/libraries/payment-icons/reference.md"), "w") as f:
    f.write(reference_md)

# ── individual icon JSON files (minimal valid icon payloads) ─────────────────
def make_icon(name, color):
    """Create a minimal icon JSON matching the expected format used by add-icon-to-diagram.py"""
    return {
        "name": name,
        "elements": [
            {
                "id": f"icon-{name}-rect",
                "type": "rectangle",
                "x": 0,
                "y": 0,
                "width": 60,
                "height": 60,
                "strokeColor": "#000000",
                "backgroundColor": color,
                "fillStyle": "solid",
                "strokeWidth": 2,
                "roughness": 1,
                "opacity": 100,
                "groupIds": [f"grp-{name}"],
                "strokeStyle": "solid",
                "roundness": None,
                "isDeleted": False,
                "boundElements": [],
                "updated": 1,
                "link": None,
                "locked": False
            },
            {
                "id": f"icon-{name}-text",
                "type": "text",
                "x": 5,
                "y": 20,
                "width": 50,
                "height": 20,
                "text": name[:3].upper(),
                "fontSize": 14,
                "fontFamily": 5,
                "textAlign": "center",
                "verticalAlign": "middle",
                "strokeColor": "#000000",
                "backgroundColor": "transparent",
                "fillStyle": "solid",
                "strokeWidth": 1,
                "roughness": 1,
                "opacity": 100,
                "groupIds": [f"grp-{name}"],
                "strokeStyle": "solid",
                "roundness": None,
                "isDeleted": False,
                "boundElements": [],
                "updated": 1,
                "link": None,
                "locked": False
            }
        ]
    }

icon_colors = {
    "credit-card": "#a5d8ff",
    "lock": "#ffd43b",
    "database": "#b2f2bb",
    "server": "#ffc9c9",
    "gateway": "#d0bfff",
}
for icon_name, color in icon_colors.items():
    icon_data = make_icon(icon_name, color)
    icon_path = os.path.join(WORKSPACE, f"skills/excalidraw-diagram-generator/libraries/payment-icons/icons/{icon_name}.json")
    with open(icon_path, "w") as f:
        json.dump(icon_data, f, indent=2)

# ── add-icon-to-diagram.py script ────────────────────────────────────────────
add_icon_script = r'''#!/usr/bin/env python3
"""
add-icon-to-diagram.py
Adds an icon from a local icon library into an existing .excalidraw diagram.

Usage:
  python add-icon-to-diagram.py <diagram-path> <icon-name> <x> <y> [--label "Text"] [--library-path PATH] [--no-use-edit-suffix]
"""
import argparse
import json
import os
import sys
import uuid
import math

def generate_id():
    return uuid.uuid4().hex[:16]

def load_diagram(path, use_edit_suffix):
    edit_path = path + ".edit" if use_edit_suffix else path
    if os.path.exists(edit_path):
        with open(edit_path) as f:
            return json.load(f), edit_path
    with open(path) as f:
        return json.load(f), edit_path

def find_library_path(base_path, library_path_arg):
    if library_path_arg:
        return library_path_arg
    # auto-detect from script location
    script_dir = os.path.dirname(os.path.abspath(__file__))
    parent = os.path.dirname(script_dir)
    candidate = os.path.join(parent, "libraries", "payment-icons")
    return candidate

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("diagram_path")
    parser.add_argument("icon_name")
    parser.add_argument("x", type=float)
    parser.add_argument("y", type=float)
    parser.add_argument("--label", default=None)
    parser.add_argument("--library-path", default=None)
    parser.add_argument("--no-use-edit-suffix", action="store_true")
    args = parser.parse_args()

    use_edit_suffix = not args.no_use_edit_suffix
    diagram, out_path = load_diagram(args.diagram_path, use_edit_suffix)

    lib_path = find_library_path(None, args.library_path)
    icon_file = os.path.join(lib_path, "icons", f"{args.icon_name}.json")
    if not os.path.exists(icon_file):
        print(f"ERROR: Icon '{args.icon_name}' not found at {icon_file}", file=sys.stderr)
        sys.exit(1)

    with open(icon_file) as f:
        icon_data = json.load(f)

    elements = icon_data.get("elements", [])
    if not elements:
        print("ERROR: Icon has no elements", file=sys.stderr)
        sys.exit(1)

    # Calculate bounding box
    min_x = min(e["x"] for e in elements)
    min_y = min(e["y"] for e in elements)

    id_map = {}
    new_group_id = generate_id()
    new_elements = []
    for elem in elements:
        new_elem = dict(elem)
        old_id = new_elem["id"]
        new_id = generate_id()
        id_map[old_id] = new_id
        new_elem["id"] = new_id
        new_elem["x"] = elem["x"] - min_x + args.x
        new_elem["y"] = elem["y"] - min_y + args.y
        if new_elem.get("groupIds"):
            new_elem["groupIds"] = [new_group_id]
        new_elements.append(new_elem)

    if args.label:
        max_x = max(e["x"] - min_x + args.x + e.get("width", 0) for e in elements)
        max_y = max(e["y"] - min_y + args.y + e.get("height", 0) for e in elements)
        icon_width = max_x - args.x
        label_elem = {
            "id": generate_id(),
            "type": "text",
            "x": args.x,
            "y": max_y + 5,
            "width": icon_width,
            "height": 20,
            "text": args.label,
            "fontSize": 16,
            "fontFamily": 5,
            "textAlign": "center",
            "verticalAlign": "top",
            "strokeColor": "#1e1e1e",
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 1,
            "roughness": 1,
            "opacity": 100,
            "groupIds": [],
            "strokeStyle": "solid",
            "roundness": None,
            "isDeleted": False,
            "boundElements": [],
            "updated": 1,
            "link": None,
            "locked": False
        }
        new_elements.append(label_elem)

    diagram.setdefault("elements", []).extend(new_elements)

    with open(out_path, "w") as f:
        json.dump(diagram, f, indent=2)
    print(f"Icon '{args.icon_name}' added to {out_path}")

if __name__ == "__main__":
    main()
'''

add_arrow_script = r'''#!/usr/bin/env python3
"""
add-arrow.py
Adds an arrow between two coordinate points in an existing .excalidraw diagram.

Usage:
  python add-arrow.py <diagram-path> <from-x> <from-y> <to-x> <to-y> [--label "Text"] [--style solid|dashed|dotted] [--color HEX] [--no-use-edit-suffix]
"""
import argparse
import json
import os
import sys
import uuid

def generate_id():
    return uuid.uuid4().hex[:16]

def load_diagram(path, use_edit_suffix):
    edit_path = path + ".edit" if use_edit_suffix else path
    if os.path.exists(edit_path):
        with open(edit_path) as f:
            return json.load(f), edit_path
    with open(path) as f:
        return json.load(f), edit_path

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("diagram_path")
    parser.add_argument("from_x", type=float)
    parser.add_argument("from_y", type=float)
    parser.add_argument("to_x", type=float)
    parser.add_argument("to_y", type=float)
    parser.add_argument("--label", default=None)
    parser.add_argument("--style", default="solid", choices=["solid","dashed","dotted"])
    parser.add_argument("--color", default="#1e1e1e")
    parser.add_argument("--no-use-edit-suffix", action="store_true")
    args = parser.parse_args()

    use_edit_suffix = not args.no_use_edit_suffix
    diagram, out_path = load_diagram(args.diagram_path, use_edit_suffix)

    arrow = {
        "id": generate_id(),
        "type": "arrow",
        "x": args.from_x,
        "y": args.from_y,
        "width": abs(args.to_x - args.from_x),
        "height": abs(args.to_y - args.from_y),
        "strokeColor": args.color,
        "backgroundColor": "transparent",
        "fillStyle": "solid",
        "strokeWidth": 2,
        "strokeStyle": args.style,
        "roughness": 1,
        "opacity": 100,
        "groupIds": [],
        "roundness": {"type": 2},
        "isDeleted": False,
        "boundElements": [],
        "updated": 1,
        "link": None,
        "locked": False,
        "points": [[0, 0], [args.to_x - args.from_x, args.to_y - args.from_y]],
        "lastCommittedPoint": None,
        "startBinding": None,
        "endBinding": None,
        "startArrowhead": None,
        "endArrowhead": "arrow"
    }

    if args.label:
        dx = args.to_x - args.from_x
        dy = args.to_y - args.from_y
        mid_x = args.from_x + dx / 2
        mid_y = args.from_y + dy / 2
        label_elem = {
            "id": generate_id(),
            "type": "text",
            "x": mid_x - 40,
            "y": mid_y - 12,
            "width": 80,
            "height": 20,
            "text": args.label,
            "fontSize": 14,
            "fontFamily": 5,
            "textAlign": "center",
            "verticalAlign": "middle",
            "strokeColor": args.color,
            "backgroundColor": "transparent",
            "fillStyle": "solid",
            "strokeWidth": 1,
            "strokeStyle": "solid",
            "roughness": 1,
            "opacity": 100,
            "groupIds": [],
            "roundness": None,
            "isDeleted": False,
            "boundElements": [],
            "updated": 1,
            "link": None,
            "locked": False
        }
        diagram.setdefault("elements", []).append(label_elem)

    diagram.setdefault("elements", []).append(arrow)

    with open(out_path, "w") as f:
        json.dump(diagram, f, indent=2)
    print(f"Arrow added to {out_path}")

if __name__ == "__main__":
    main()
'''

# Write scripts
scripts_base = os.path.join(WORKSPACE, "skills/excalidraw-diagram-generator/scripts")
with open(os.path.join(scripts_base, "add-icon-to-diagram.py"), "w") as f:
    f.write(add_icon_script)
with open(os.path.join(scripts_base, "add-arrow.py"), "w") as f:
    f.write(add_arrow_script)

# ── templates (minimal, valid starters — NOT the target output) ───────────────
flowchart_template = {
    "type": "excalidraw",
    "version": 2,
    "source": "https://excalidraw.com",
    "elements": [],
    "appState": {"viewBackgroundColor": "#ffffff", "gridSize": 20},
    "files": {}
}
with open(os.path.join(WORKSPACE, "skills/excalidraw-diagram-generator/templates/flowchart-template.json"), "w") as f:
    json.dump(flowchart_template, f, indent=2)

relationship_template = dict(flowchart_template)
with open(os.path.join(WORKSPACE, "skills/excalidraw-diagram-generator/templates/relationship-template.json"), "w") as f:
    json.dump(relationship_template, f, indent=2)

mindmap_template = dict(flowchart_template)
with open(os.path.join(WORKSPACE, "skills/excalidraw-diagram-generator/templates/mindmap-template.json"), "w") as f:
    json.dump(mindmap_template, f, indent=2)

# ── references (stub, not exploitable) ───────────────────────────────────────
with open(os.path.join(WORKSPACE, "skills/excalidraw-diagram-generator/references/excalidraw-schema.md"), "w") as f:
    f.write("# Excalidraw Schema\nSee SKILL.md for full details.\n")
with open(os.path.join(WORKSPACE, "skills/excalidraw-diagram-generator/references/element-types.md"), "w") as f:
    f.write("# Element Types\nrectangle, ellipse, diamond, arrow, text\n")

print("Workspace generated successfully.")
print("Key paths:")
print("  scripts: skills/excalidraw-diagram-generator/scripts/")
print("  library: skills/excalidraw-diagram-generator/libraries/payment-icons/")