#!/usr/bin/env python3
"""
Generate the sandbox workspace for the OmniSkill integration task.
Creates the omni-skill project with its CLI scripts, a raw plugin to be packaged,
and assorted distractor files.
"""
import os
import json
import stat
import textwrap
from pathlib import Path
from datetime import datetime

WORKSPACE = Path("/workspace")

# ─────────────────────────────────────────────────────────────
# 1.  omni-skill project skeleton
# ─────────────────────────────────────────────────────────────
OMNI = WORKSPACE / "omni-skill"

dirs_to_create = [
    OMNI / "src" / "cli",
    OMNI / "src" / "gateway",
    OMNI / "src" / "dispatcher",
    OMNI / "src" / "core",
    OMNI / "data" / "registry",
    OMNI / "logs",
    OMNI / "tests",
    WORKSPACE / "raw_plugins" / "text_classifier" / "models",
    WORKSPACE / "raw_plugins" / "text_classifier" / "utils",
    WORKSPACE / "packages",          # packager output goes here
    WORKSPACE / "projects" / "alpha" / "src",
    WORKSPACE / "projects" / "beta" / "configs",
    WORKSPACE / "archived_tools" / "v1",
    WORKSPACE / "archived_tools" / "v2",
    WORKSPACE / "shared_libs",
]

for d in dirs_to_create:
    d.mkdir(parents=True, exist_ok=True)

# ─────────────────────────────────────────────────────────────
# 2.  omni_packager.py   (must be run from ./omni-skill/)
# ─────────────────────────────────────────────────────────────
omni_packager = OMNI / "src" / "cli" / "omni_packager.py"
omni_packager.write_text(textwrap.dedent(r'''
#!/usr/bin/env python3
"""
omni_packager.py - OmniSkill built-in packager.
MUST be invoked from the ./omni-skill project root.
"""
import argparse
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

REQUIRED_CWD_MARKER = "src"   # omni-skill root must contain this sub-dir


def _assert_project_root():
    cwd = Path.cwd()
    marker = cwd / REQUIRED_CWD_MARKER
    if not marker.exists():
        print(
            f"[omni_packager] ERROR: Must be executed from the omni-skill "
            f"project root (current dir '{cwd}' has no '{REQUIRED_CWD_MARKER}/' sub-directory).",
            file=sys.stderr,
        )
        sys.exit(2)
    return cwd


def main():
    parser = argparse.ArgumentParser(description="OmniSkill Packager")
    parser.add_argument("--source", required=True, help="Path to raw plugin directory")
    parser.add_argument("--target", required=True, help="Destination package path")
    args = parser.parse_args()

    project_root = _assert_project_root()

    source = Path(args.source).resolve()
    target = Path(args.target).resolve()

    if not source.exists():
        print(f"[omni_packager] ERROR: source '{source}' does not exist.", file=sys.stderr)
        sys.exit(1)

    target.mkdir(parents=True, exist_ok=True)

    # Copy source files
    for item in source.rglob("*"):
        if item.is_file():
            rel = item.relative_to(source)
            dest = target / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(item, dest)

    # Generate manifest
    files = [str(p.relative_to(target)) for p in target.rglob("*") if p.is_file()]
    manifest = {
        "schema_version": "1.0",
        "packaged_by": "omni_packager",
        "source": str(source),
        "target": str(target),
        "project_root": str(project_root),
        "packed_at": datetime.now(timezone.utc).isoformat(),
        "files": sorted(files),
    }
    (target / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False))

    # Generate __init__.py stub
    init_content = f'# Auto-generated by omni_packager\n# Source: {source}\n__omni_package__ = True\n'
    (target / "__init__.py").write_text(init_content)

    print(f"[omni_packager] SUCCESS: Packaged '{source}' -> '{target}'")
    print(f"[omni_packager] manifest.json written with {len(files)} source file(s).")


if __name__ == "__main__":
    main()
'''.lstrip()))
omni_packager.chmod(omni_packager.stat().st_mode | stat.S_IEXEC)

# ─────────────────────────────────────────────────────────────
# 3.  omni_ctl.py
# ─────────────────────────────────────────────────────────────
omni_ctl = OMNI / "src" / "cli" / "omni_ctl.py"
omni_ctl.write_text(textwrap.dedent(r'''
#!/usr/bin/env python3
"""
omni_ctl.py - OmniSkill Control CLI.
Subcommands: register | dispatch | rollback | list
MUST be invoked from the ./omni-skill project root.
"""
import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

REQUIRED_CWD_MARKER = "src"
REGISTRY_FILE = Path("data/registry/registry.json")
SKILL_MD_FILE = Path("../SKILL.md")          # relative to omni-skill root
REGISTRY_MARKER_START = "<!-- OMNI_REGISTRY_START -->"
REGISTRY_MARKER_END   = "<!-- OMNI_REGISTRY_END -->"

VALID_RUNTIME_TYPES = {"python", "node", "bash", "wasm"}

OMNI_RESPONSE_SCHEMA_VERSION = "1.0"


def _assert_project_root():
    cwd = Path.cwd()
    if not (cwd / REQUIRED_CWD_MARKER).exists():
        print(
            f"[omni_ctl] ERROR: Must be executed from the omni-skill project root "
            f"(no '{REQUIRED_CWD_MARKER}/' found in '{cwd}').",
            file=sys.stderr,
        )
        sys.exit(2)
    return cwd


def _load_registry():
    path = REGISTRY_FILE
    if path.exists():
        return json.loads(path.read_text())
    return {"skills": [], "last_updated": None}


def _save_registry(reg):
    REGISTRY_FILE.parent.mkdir(parents=True, exist_ok=True)
    REGISTRY_FILE.write_text(json.dumps(reg, indent=2, ensure_ascii=False))


def _update_skill_md(reg):
    """Rewrite the OMNI_REGISTRY block inside SKILL.md (one level up)."""
    skill_md = SKILL_MD_FILE
    if not skill_md.exists():
        return  # silently skip if SKILL.md not present at expected path
    content = skill_md.read_text(encoding="utf-8")
    start_idx = content.find(REGISTRY_MARKER_START)
    end_idx   = content.find(REGISTRY_MARKER_END)
    if start_idx == -1 or end_idx == -1:
        return
    header = content[: start_idx + len(REGISTRY_MARKER_START)]
    footer = content[end_idx:]
    lines  = ["\n## 当前可用子技能列表 (Available Sub-Skills)\n"]
    if not reg["skills"]:
        lines.append("\n*当前暂无已注册的子技能。*\n\n*(此列表由 `omni_ctl` 自动维护，请勿手动修改)*\n")
    else:
        lines.append("\n| 名称 | runtime-type | 注册时间 |\n|------|-------------|----------|\n")
        for s in reg["skills"]:
            lines.append(f"| {s['name']} | {s['runtime_type']} | {s['registered_at']} |\n")
        lines.append("\n*(此列表由 `omni_ctl` 自动维护，请勿手动修改)*\n")
    new_content = header + "".join(lines) + footer
    skill_md.write_text(new_content, encoding="utf-8")


def cmd_register(args):
    _assert_project_root()
    name = args.name
    runtime_type = args.runtime_type

    if runtime_type not in VALID_RUNTIME_TYPES:
        print(
            f"[omni_ctl] ERROR: --runtime-type '{runtime_type}' is invalid. "
            f"Choose from: {sorted(VALID_RUNTIME_TYPES)}",
            file=sys.stderr,
        )
        sys.exit(1)

    reg = _load_registry()

    # Check duplicate
    existing = [s for s in reg["skills"] if s["name"] == name]
    if existing:
        print(f"[omni_ctl] WARN: Skill '{name}' already registered. Updating entry.")
        reg["skills"] = [s for s in reg["skills"] if s["name"] != name]

    entry = {
        "name": name,
        "runtime_type": runtime_type,
        "registered_at": datetime.now(timezone.utc).isoformat(),
        "status": "active",
    }
    reg["skills"].append(entry)
    reg["last_updated"] = datetime.now(timezone.utc).isoformat()
    _save_registry(reg)
    _update_skill_md(reg)

    print(f"[omni_ctl] SUCCESS: Skill '{name}' registered with runtime-type='{runtime_type}'.")
    print(f"[omni_ctl] Registry updated: {REGISTRY_FILE}")
    print(f"[omni_ctl] LRU lazy-load will mount this skill on next dispatch.")


def cmd_dispatch(args):
    _assert_project_root()

    # Parse payload
    if args.payload_file:
        payload_str = Path(args.payload_file).read_text()
    elif args.payload:
        payload_str = args.payload
    else:
        print("[omni_ctl] ERROR: Provide --payload JSON or --payload-file.", file=sys.stderr)
        sys.exit(1)

    try:
        request = json.loads(payload_str)
    except json.JSONDecodeError as e:
        print(f"[omni_ctl] ERROR: Invalid JSON payload: {e}", file=sys.stderr)
        sys.exit(1)

    required_fields = {"route_type", "payload", "mode", "args", "kwargs"}
    missing = required_fields - set(request.keys())
    if missing:
        print(
            f"[omni_ctl] ERROR: Request JSON is missing required fields: {sorted(missing)}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Validate mode
    if request["mode"] not in ("sync", "async"):
        print(f"[omni_ctl] ERROR: 'mode' must be 'sync' or 'async'.", file=sys.stderr)
        sys.exit(1)

    # Validate registered skill for the route
    reg = _load_registry()
    route = request["route_type"]

    # Build OmniResponse
    response = {
        "schema_version": OMNI_RESPONSE_SCHEMA_VERSION,
        "status": "ok",
        "route_type": route,
        "mode": request["mode"],
        "dispatched_at": datetime.now(timezone.utc).isoformat(),
        "result": {
            "message": f"Dispatched '{request['payload']}' via route '{route}' successfully.",
            "args": request["args"],
            "kwargs": request["kwargs"],
        },
        "registered_skills": [s["name"] for s in reg["skills"]],
    }

    out = json.dumps(response, indent=2, ensure_ascii=False)

    if args.output:
        Path(args.output).write_text(out, encoding="utf-8")
        print(f"[omni_ctl] OmniResponse written to '{args.output}'.")
    else:
        print(out)


def cmd_rollback(args):
    _assert_project_root()
    reg = _load_registry()
    if not reg["skills"]:
        print("[omni_ctl] INFO: Nothing to rollback (registry is empty).")
        return
    removed = reg["skills"].pop()
    reg["last_updated"] = datetime.now(timezone.utc).isoformat()
    _save_registry(reg)
    _update_skill_md(reg)
    print(f"[omni_ctl] ROLLBACK: Removed last registered skill '{removed['name']}'.")


def cmd_list(args):
    _assert_project_root()
    reg = _load_registry()
    if not reg["skills"]:
        print("[omni_ctl] No skills currently registered.")
        return
    for s in reg["skills"]:
        print(f"  - {s['name']} ({s['runtime_type']}) [{s['status']}]")


def main():
    parser = argparse.ArgumentParser(description="OmniSkill Control CLI")
    sub = parser.add_subparsers(dest="command")

    # register
    p_reg = sub.add_parser("register")
    p_reg.add_argument("--name", required=True)
    p_reg.add_argument("--runtime-type", required=True, dest="runtime_type")

    # dispatch
    p_dis = sub.add_parser("dispatch")
    p_dis.add_argument("--payload", default=None)
    p_dis.add_argument("--payload-file", default=None, dest="payload_file")
    p_dis.add_argument("--output", default=None, help="Write OmniResponse JSON to this file")

    # rollback
    sub.add_parser("rollback")

    # list
    sub.add_parser("list")

    args = parser.parse_args()
    if args.command == "register":
        cmd_register(args)
    elif args.command == "dispatch":
        cmd_dispatch(args)
    elif args.command == "rollback":
        cmd_rollback(args)
    elif args.command == "list":
        cmd_list(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
'''.lstrip()))
omni_ctl.chmod(omni_ctl.stat().st_mode | stat.S_IEXEC)

# ─────────────────────────────────────────────────────────────
# 4.  gateway.py
# ─────────────────────────────────────────────────────────────
gateway_py = OMNI / "src" / "gateway" / "gateway.py"
gateway_py.write_text(textwrap.dedent(r'''
#!/usr/bin/env python3
"""OmniSkill Gateway - thin HTTP facade (not required for CLI workflow)."""
print("[gateway] Gateway interface available. Use omni_ctl.py for CLI dispatch.")
'''.lstrip()))

# ─────────────────────────────────────────────────────────────
# 5.  Other omni-skill project files (distractors & support)
# ─────────────────────────────────────────────────────────────
(OMNI / "src" / "dispatcher" / "dispatcher.py").write_text(
    '"""Internal dispatcher - invoked by omni_ctl automatically."""\n'
)
(OMNI / "src" / "core" / "lru_cache.py").write_text(
    '"""LRU lazy-load cache used by the dispatcher."""\n'
)
(OMNI / "src" / "core" / "__init__.py").write_text("")
(OMNI / "src" / "__init__.py").write_text("")
(OMNI / "tests" / "test_packager.py").write_text(
    '"""Placeholder test suite for omni_packager."""\n'
)
(OMNI / "logs" / ".gitkeep").write_text("")

# Project config (distractor)
(OMNI / "omni_config.toml").write_text(textwrap.dedent("""\
    [project]
    name = "omni-skill"
    version = "2.1.0"
    schema = "omni-v2"

    [dispatcher]
    lru_ttl_seconds = 300
    max_workers = 8
    rollback_window_seconds = 30
"""))

# ─────────────────────────────────────────────────────────────
# 6.  SKILL.md  (lives one level up from omni-skill/)
# ─────────────────────────────────────────────────────────────
skill_md = WORKSPACE / "SKILL.md"
skill_md.write_text(textwrap.dedent("""\
    ---
    name: "omni-skill"
    description: "OmniSkill 通用技能调度与执行中枢 by @Elohia (https://github.com/Elohia/omni-skill-core)。当用户请求执行任何特定的任务（如代码生成、文本润色、逻辑审计、数据处理、测试等）或系统触发任何自动化流程（如文件保存、提交检查）时，必须立即调用此 Skill。"
    ---

    # OmniSkill (通用技能调度器)

    ## When to Use

    **CRITICAL: You MUST invoke this skill IMMEDIATELY as your FIRST action when:**
    - 用户明确要求执行某项特定任务（如"帮我润色这段文字"、"检查一下代码逻辑"、"生成一个基础设定"等）时。
    - 系统自动触发了某些生命周期事件（如"保存前检查"、"构建后部署"等）时。
    - 在需要多步处理或调用外部工具前，必须优先通过 OmniSkill 进行意图识别和任务分发。

    **DO NOT:**
    - 在没有经过调度器分配的情况下，直接手动执行复杂的外部环境操作。
    - 绕过 OmniSkill 直接调用零散的、未经包装的旧脚本。

    ## 渐进式调度规范 (执行逻辑)
    当你（大模型）被触发并进入本 Skill 时，请遵循以下普适化处理流程：

    ### 步骤 1：意图识别与参数提取
    - 分析用户的输入或系统 Hook 的上下文。
    - 提取关键信息，明确需要执行的任务类型（如 `route_type="nlp"`, `payload="润色文本"`）。

    ### 步骤 2：构建请求与下发
    - 根据提取的信息，构建标准化的 JSON 请求格式。
    - 将请求发送至 OmniSkill 的网关（例如通过 CLI 工具 `omni_ctl.py` 触发，或调用 `src/gateway/gateway.py` 暴露的接口）。
    - **示例结构**：
      ```json
      {
        "route_type": "nlp",
        "payload": "执行逻辑审计",
        "mode": "sync",
        "args": ["..."],
        "kwargs": {"context": "..."}
      }
      ```

    ### 步骤 3：结果处理与响应
    - 等待底层调度引擎（Dispatcher）和具体插件（Plugin）的执行结果。
    - 捕获返回的 `OmniResponse` 或标准输出。
    - 将执行结果解析为人类可读的语言（遵循纯中文输出原则），并返回给用户。

    ## 扩展与管理机制 (如何接入新技能)
    OmniSkill 具备极强的普适性和扩展性。如果用户希望添加新的技能或接入外部现成的工具包：

    1. **统一打包**：使用内置的打包器将外部目录转化为标准核心包。
       ```bash
       # 必须进入项目目录执行
       cd ./omni-skill
       python src/cli/omni_packager.py --source <原始路径> --target <目标包路径>
       ```
    2. **注册与挂载**：将生成的包注册到调度中枢。
       ```bash
       python src/cli/omni_ctl.py register --name <技能名称> --runtime-type <运行环境>
       ```
    3. **即时生效**：注册完成后，无需重启系统。下次调度时，底层引擎将通过 LRU 懒加载机制自动挂载并执行该技能。若发生冲突或异常，可在 30 秒内执行 `omni_ctl.py rollback` 安全回滚。

    <!-- OMNI_REGISTRY_START -->
    ## 当前可用子技能列表 (Available Sub-Skills)

    *当前暂无已注册的子技能。*

    *(此列表由 `omni_ctl` 自动维护，请勿手动修改)*
    <!-- OMNI_REGISTRY_END -->
"""))

# ─────────────────────────────────────────────────────────────
# 7.  Raw plugin: text_classifier  (the thing to be packaged)
# ─────────────────────────────────────────────────────────────
raw_tc = WORKSPACE / "raw_plugins" / "text_classifier"

(raw_tc / "classifier.py").write_text(textwrap.dedent("""\
    \"\"\"Lightweight text classification module.\"\"\"

    def classify(text: str) -> dict:
        keywords_pos = ["good", "great", "excellent", "love", "best"]
        keywords_neg = ["bad", "terrible", "worst", "hate", "awful"]
        text_lower = text.lower()
        pos = sum(1 for w in keywords_pos if w in text_lower)
        neg = sum(1 for w in keywords_neg if w in text_lower)
        if pos > neg:
            label = "positive"
        elif neg > pos:
            label = "negative"
        else:
            label = "neutral"
        return {"label": label, "pos_score": pos, "neg_score": neg}
"""))

(raw_tc / "models" / "base_model.py").write_text(
    '"""Placeholder base model for text classification."""\n\nMODEL_VERSION = "0.3.1"\n'
)

(raw_tc / "utils" / "preprocessor.py").write_text(textwrap.dedent("""\
    \"\"\"Text preprocessor utilities.\"\"\"
    import re

    def clean(text: str) -> str:
        text = re.sub(r"\\s+", " ", text).strip()
        return text.lower()
"""))

(raw_tc / "utils" / "tokenizer.py").write_text(
    '"""Simple whitespace tokenizer."""\n\ndef tokenize(text): return text.split()\n'
)

(raw_tc / "requirements.txt").write_text("# No external deps\n")

# ─────────────────────────────────────────────────────────────
# 8.  Distractor files (unrelated projects)
# ─────────────────────────────────────────────────────────────
(WORKSPACE / "projects" / "alpha" / "src" / "main.py").write_text(
    "# Project Alpha - unrelated to OmniSkill\nprint('alpha')\n"
)
(WORKSPACE / "projects" / "beta" / "configs" / "settings.yaml").write_text(
    "env: production\ndebug: false\nport: 8080\n"
)
(WORKSPACE / "projects" / "beta" / "configs" / "db.yaml").write_text(
    "host: localhost\nport: 5432\nname: beta_db\n"
)
(WORKSPACE / "archived_tools" / "v1" / "legacy_dispatch.py").write_text(
    '"""Deprecated dispatcher - do NOT use. Replaced by OmniSkill."""\nraise DeprecationWarning("legacy")\n'
)
(WORKSPACE / "archived_tools" / "v2" / "old_packager.sh").write_text(
    "#!/bin/bash\n# DEPRECATED: use omni_packager.py instead\necho 'deprecated'\n"
)
(WORKSPACE / "shared_libs" / "common_utils.py").write_text(
    "def noop(): pass\n"
)
(WORKSPACE / "shared_libs" / "config_loader.py").write_text(
    "def load_config(path): return {}\n"
)

# ─────────────────────────────────────────────────────────────
# 9.  A misleading stub omni_ctl in archived_tools (trap!)
# ─────────────────────────────────────────────────────────────
(WORKSPACE / "archived_tools" / "v2" / "omni_ctl_old.py").write_text(textwrap.dedent("""\
    #!/usr/bin/env python3
    \"\"\"OLD omni_ctl stub - DO NOT USE. This version does not update the registry.\"\"\"
    import sys
    print("[OLD omni_ctl] ERROR: This is a deprecated stub. "
          "Use omni-skill/src/cli/omni_ctl.py instead.", file=sys.stderr)
    sys.exit(99)
"""))

print("Workspace generated successfully.")
print(f"  omni-skill project:  {OMNI}")
print(f"  raw plugin:          {raw_tc}")
print(f"  SKILL.md:            {skill_md}")