import os
import json
import random
from pathlib import Path

random.seed(42)

workspace = Path("/workspace")

# ── Directory structure ──────────────────────────────────────────────
dirs = [
    "config",
    "memory",
    "data/raw/premier_league",
    "data/raw/la_liga",
    "data/raw/bundesliga",
    "data/processed",
    "data/odds",
    "scripts",
    "logs",
    "reports/weekly",
    "reports/monthly",
    "cache/teams",
    "cache/odds",
]
for d in dirs:
    (workspace / d).mkdir(parents=True, exist_ok=True)

# ── config/leagues.json (existing, correct) ──────────────────────────
leagues_cfg = {
    "leagues": [
        {"id": "EPL", "name": "英超", "country": "England", "active": True},
        {"id": "LAL", "name": "西甲", "country": "Spain",   "active": True},
        {"id": "BUN", "name": "德甲", "country": "Germany", "active": True},
        {"id": "SA",  "name": "意甲", "country": "Italy",   "active": True},
        {"id": "L1",  "name": "法甲", "country": "France",  "active": False},
    ]
}
(workspace / "config/leagues.json").write_text(json.dumps(leagues_cfg, ensure_ascii=False, indent=2))

# ── Distractor files ─────────────────────────────────────────────────
(workspace / "data/raw/premier_league/fixtures_2024.csv").write_text(
    "date,home,away,competition\n2024-08-10,曼城,切尔西,EPL\n2024-08-11,曼联,富勒姆,EPL\n"
)
(workspace / "data/raw/la_liga/fixtures_2024.csv").write_text(
    "date,home,away,competition\n2024-08-18,皇马,瓦伦西亚,LAL\n2024-08-19,巴萨,毕尔巴鄂,LAL\n"
)
(workspace / "data/raw/bundesliga/fixtures_2024.csv").write_text(
    "date,home,away,competition\n2024-08-23,拜仁,勒沃库森,BUN\n"
)
(workspace / "data/odds/epl_odds_week1.json").write_text(json.dumps({
    "week": 1,
    "odds": [
        {"match": "曼城 vs 切尔西", "home_win": 1.85, "draw": 3.50, "away_win": 4.20},
        {"match": "曼联 vs 富勒姆",  "home_win": 2.10, "draw": 3.20, "away_win": 3.60},
    ]
}, ensure_ascii=False, indent=2))
(workspace / "data/odds/lal_odds_week1.json").write_text(json.dumps({
    "week": 1,
    "odds": [
        {"match": "皇马 vs 瓦伦西亚", "home_win": 1.55, "draw": 4.00, "away_win": 6.50},
    ]
}, ensure_ascii=False, indent=2))
(workspace / "data/processed/team_form.json").write_text(json.dumps({
    "曼城": {"recent_5": ["W","W","W","D","W"], "goals_scored": 14, "goals_conceded": 3},
    "切尔西": {"recent_5": ["L","W","D","W","L"], "goals_scored": 8, "goals_conceded": 9},
    "曼联": {"recent_5": ["W","D","L","W","W"], "goals_scored": 9, "goals_conceded": 7},
    "富勒姆": {"recent_5": ["D","L","W","D","L"], "goals_scored": 6, "goals_conceded": 8},
    "皇马": {"recent_5": ["W","W","W","W","W"], "goals_scored": 18, "goals_conceded": 2},
    "利物浦": {"recent_5": ["W","W","D","W","W"], "goals_scored": 15, "goals_conceded": 4},
    "阿森纳": {"recent_5": ["W","W","W","D","W"], "goals_scored": 13, "goals_conceded": 5},
}, ensure_ascii=False, indent=2))
(workspace / "cache/teams/injuries.json").write_text(json.dumps({
    "曼城": ["贝尔纳多·席尔瓦(膝伤,疑问)"],
    "曼联": ["拉什福德(踝伤,缺席)"],
    "皇马": [],
    "利物浦": ["路易斯·迪亚斯(轻伤,疑问)"],
}, ensure_ascii=False, indent=2))
(workspace / "cache/odds/movement_log.txt").write_text(
    "2024-08-10 曼城 vs 切尔西 home_win: 1.95 -> 1.85 (sharp money on home)\n"
    "2024-08-11 曼联 vs 富勒姆 home_win: 2.20 -> 2.10\n"
)
(workspace / "scripts/fetch_odds.py").write_text(
    "# Placeholder: would fetch live odds from provider\nprint('odds fetched')\n"
)
(workspace / "scripts/scrape_fixtures.py").write_text(
    "# Placeholder: would scrape fixtures from sports data API\nprint('fixtures scraped')\n"
)
(workspace / "logs/agent.log").write_text(
    "[2024-08-01] System initialized\n[2024-08-02] Fetched 12 fixtures\n"
)
(workspace / "reports/weekly/week1_summary.txt").write_text(
    "Week 1 summary: No predictions recorded yet. System awaiting first run.\n"
)
(workspace / "reports/monthly/august_placeholder.txt").write_text(
    "August: pending data collection.\n"
)

# ── Raw match result data (messy, unstructured — agent must interpret) ─
# These are NOT in the required memory format; they're raw inputs the agent
# must use to populate the memory files properly.
raw_results = """
# 实际比赛结果 - 原始记录 (需要整理入系统)
# 格式: 日期 | 主队 | 客队 | 比分 | 联赛

2024-08-10 | 曼城 | 切尔西 | 3-1 | EPL
2024-08-11 | 曼联 | 富勒姆 | 2-0 | EPL
2024-08-18 | 皇马 | 瓦伦西亚 | 4-0 | LAL
2024-08-24 | 利物浦 | 阿森纳 | 2-2 | EPL
2024-08-31 | 曼城 | 布莱顿 | 2-1 | EPL
"""
(workspace / "data/raw/actual_results_raw.txt").write_text(raw_results)

# ── memory/ files: intentionally ABSENT so agent must create them ─────
# predictions.json, results.json, stats.json, model.json — do NOT create

# ── A partial/broken stub to mislead naive agents ────────────────────
(workspace / "memory/.keep").write_text("# memory directory — files will be generated by agent\n")

print("Workspace initialized. memory/ JSON files are absent and must be created by the agent.")