import os
import json
import random
from pathlib import Path

random.seed(42)

workspace = Path("/workspace")
workspace.mkdir(exist_ok=True)

# ---- Create deeply nested distractor directory structure ----
dirs = [
    "market_data/fx/archives/2024",
    "market_data/fx/archives/2023",
    "market_data/commodities/silver",
    "market_data/commodities/oil",
    "market_data/equities/indices",
    "reports/weekly/drafts",
    "reports/monthly/published",
    "config/feeds",
    "config/templates",
    "scripts/parsers",
    "logs/feed_errors",
    "tmp/staging",
]
for d in dirs:
    (workspace / d).mkdir(parents=True, exist_ok=True)

# ---- Distractor files ----
(workspace / "market_data/fx/archives/2024/usd_cny_2024.csv").write_text(
    "date,open,close,high,low\n2024-01-01,7.1,7.12,7.15,7.09\n2024-06-01,7.25,7.27,7.30,7.23\n"
)
(workspace / "market_data/fx/archives/2023/usd_cny_2023.csv").write_text(
    "date,open,close,high,low\n2023-01-01,6.95,6.97,6.99,6.94\n"
)
(workspace / "market_data/commodities/silver/xag_usd_latest.json").write_text(
    json.dumps({"symbol": "XAG/USD", "price": 29.45, "change": 0.12, "change_pct": 0.41})
)
(workspace / "market_data/commodities/oil/crude_wti.json").write_text(
    json.dumps({"symbol": "WTI", "price": 78.34, "change": -0.55, "date": "2025-07-08"})
)
(workspace / "market_data/equities/indices/spy_summary.txt").write_text(
    "SPY ETF Daily Summary\nClose: 548.23\nChange: +1.12 (+0.21%)\nVolume: 72M\n"
)
(workspace / "reports/weekly/drafts/weekly_commodities_draft.txt").write_text(
    "DRAFT - Weekly Commodities Report\nNOT FOR DISTRIBUTION\nGold reviewed separately.\n"
)
(workspace / "reports/monthly/published/june_summary.pdf.txt").write_text(
    "Placeholder for June monthly report PDF.\n"
)
(workspace / "config/feeds/data_sources.yaml").write_text(
    "feeds:\n  - name: reuters_gold\n    url: https://feeds.reuters.com/gold\n    active: false\n  - name: kitco\n    url: https://www.kitco.com\n    active: true\n"
)
(workspace / "config/templates/report_header.txt").write_text(
    "INTERNAL USE ONLY\nGenerated by FinBot v2.1\n"
)
(workspace / "scripts/parsers/fx_parser.py").write_text(
    "# FX data parser stub\ndef parse_fx(path):\n    pass\n"
)
(workspace / "logs/feed_errors/feed_errors_2025-07-08.log").write_text(
    "ERROR: Reuters feed timeout at 09:31:02\nWARN: Kitco latency 3200ms\nINFO: Backup feed activated\n"
)
(workspace / "tmp/staging/raw_dump_20250708.bin").write_text(
    "BINARY_PLACEHOLDER: do not parse\n"
)

# ---- THE ACTUAL PROBLEM: Messy raw gold price data files ----

# International gold price data (XAU/USD) - messy CSV with noise
(workspace / "market_data/commodities/gold/xau_usd_20250708.csv").parent.mkdir(parents=True, exist_ok=True)
(workspace / "market_data/commodities/gold/xau_usd_20250708.csv").write_text(
    """# Raw feed from backup source - Kitco API dump - 2025-07-08T16:00:00Z
# Fields: timestamp,open,high,low,close,volume,source
# NOTE: Some rows may have feed errors (marked with ERR)
timestamp,open,high,low,close,volume,source
2025-07-08T09:30:00Z,3318.50,3318.50,3318.50,3318.50,0,kitco
2025-07-08T10:00:00Z,3318.50,3325.40,3312.80,3320.15,1823,kitco
2025-07-08T11:00:00Z,3320.15,3331.60,3318.00,3328.90,2105,kitco
2025-07-08T12:00:00Z,3328.90,3335.20,3322.10,3330.45,1987,kitco
2025-07-08T13:00:00Z,3330.45,3341.80,3328.50,3338.72,2341,kitco
2025-07-08T14:00:00Z,ERR,ERR,ERR,ERR,ERR,kitco_backup
2025-07-08T15:00:00Z,3338.72,3345.60,3334.20,3342.18,2089,kitco
2025-07-08T16:00:00Z,3342.18,3348.90,3337.50,3344.65,1756,kitco
"""
)

# Previous day close for change calculation
(workspace / "market_data/commodities/gold/xau_usd_20250707_close.txt").write_text(
    """# Previous trading day close - 2025-07-07
# Symbol: XAU/USD
# Source: Kitco
PREV_CLOSE=3298.30
PREV_DATE=2025-07-07
"""
)

# Domestic gold price data (CNY/gram) - JSON with some noise fields
(workspace / "market_data/commodities/gold/domestic_gold_20250708.json").write_text(
    json.dumps({
        "report_date": "2025-07-08",
        "source": "中国黄金协会",
        "fetch_time": "2025-07-08T10:30:00+08:00",
        "prices": {
            "AU9999": {
                "today_price": 782.50,
                "yesterday_price": 765.30,
                "unit": "CNY/gram",
                "product": "足金9999",
                "note": "上海黄金交易所参考价"
            },
            "AU9995": {
                "today_price": 780.00,
                "yesterday_price": 763.10,
                "unit": "CNY/gram",
                "product": "足金9995"
            }
        },
        "metadata": {
            "usd_cny_rate": 7.2453,
            "data_quality": "estimated",
            "stale_warning": False
        }
    }, ensure_ascii=False, indent=2)
)

# Market news/factors - unstructured text
(workspace / "market_data/commodities/gold/market_factors_20250708.txt").write_text(
    """GOLD MARKET FACTORS - 2025-07-08
Source: Internal Analyst Notes

USD INDEX (DXY): 102.45, down -0.38 from yesterday (weakening dollar supportive for gold)
FED RATE OUTLOOK: Fed minutes released yesterday showed 2 members favoring rate cut in Sept 2025. 
  Current Fed Funds Rate: 5.25-5.50%. Market pricing 67% chance of Sept cut.
GEOPOLITICAL: Ongoing Middle East tensions. Safe-haven demand elevated.
  - Regional conflict risk index: HIGH
  - Flight-to-safety flows observed in morning session
TREND DATA:
  1-week ago close: 3265.40
  1-month ago close: 3180.00
  3-month ago close: 2980.50
ANALYST NOTE: Gold testing resistance at 3350. Break above could target 3400.
"""
)

# A stale/old gold report to act as distractor
(workspace / "reports/weekly/drafts/gold_brief_20250701.txt").write_text(
    "Gold Brief - 2025-07-01\nXAU/USD: 3265.40 (STALE - DO NOT USE)\nThis is an old draft, not current.\n"
)

print("Workspace generated successfully.")
print(f"Files created in {workspace}")