#!/bin/bash
set -e

# Create the mock sessions_spawn tool that the agent will call
# This simulates the sessions_spawn function as a CLI tool
cat > /usr/local/bin/sessions_spawn << 'PYEOF'
#!/usr/bin/env python3
"""
Mock implementation of sessions_spawn.
Accepts --message, --model, --label arguments and logs the call.
"""
import sys
import json
import argparse
import os
import time
from datetime import datetime

parser = argparse.ArgumentParser()
parser.add_argument("--message", required=True, help="Full task description")
parser.add_argument("--model", required=True, help="Model identifier")
parser.add_argument("--label", required=True, help="Short task label")
args = parser.parse_args()

VALID_MODELS = [
    "anthropic/claude-haiku-4-5",
    "anthropic/claude-sonnet-4-5",
    "anthropic/claude-opus-4-6"
]

if args.model not in VALID_MODELS:
    print(f"ERROR: Unknown model '{args.model}'. Valid models: {VALID_MODELS}", file=sys.stderr)
    sys.exit(1)

# Log the call to a session log file
log_dir = "/workspace/ai_assistant/sessions"
os.makedirs(log_dir, exist_ok=True)
log_file = os.path.join(log_dir, "spawn_log.jsonl")

entry = {
    "timestamp": datetime.utcnow().isoformat(),
    "model": args.model,
    "label": args.label,
    "message": args.message
}

with open(log_file, "a") as f:
    f.write(json.dumps(entry) + "\n")

# Simulate model response - return a mock response indicating model used
model_short = args.model.split("/")[-1]
print(f"[Model Used: {args.model}] Response for task '{args.label}': Mock response generated by {model_short}.")
PYEOF

chmod +x /usr/local/bin/sessions_spawn

# Also create a Python-callable version as a module
mkdir -p /workspace/lib
cat > /workspace/lib/sessions_spawn.py << 'PYEOF'
"""
Python interface for sessions_spawn.
Can be called as a function or imported.
"""
import json
import os
import subprocess
import sys
from datetime import datetime

VALID_MODELS = [
    "anthropic/claude-haiku-4-5",
    "anthropic/claude-sonnet-4-5",
    "anthropic/claude-opus-4-6"
]

def sessions_spawn(message: str, model: str, label: str) -> str:
    """Spawn a session with the given model."""
    if model not in VALID_MODELS:
        raise ValueError(f"Unknown model '{model}'. Valid: {VALID_MODELS}")
    
    log_dir = "/workspace/ai_assistant/sessions"
    os.makedirs(log_dir, exist_ok=True)
    log_file = os.path.join(log_dir, "spawn_log.jsonl")
    
    entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "model": model,
        "label": label,
        "message": message
    }
    
    with open(log_file, "a") as f:
        f.write(json.dumps(entry) + "\n")
    
    model_short = model.split("/")[-1]
    response = f"[Model Used: {model}] Response for task '{label}': Mock response generated by {model_short}."
    return response

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--message", required=True)
    parser.add_argument("--model", required=True)
    parser.add_argument("--label", required=True)
    args = parser.parse_args()
    result = sessions_spawn(message=args.message, model=args.model, label=args.label)
    print(result)
PYEOF

chmod +x /workspace/lib/sessions_spawn.py

echo "Mock sessions_spawn tool installed at /usr/local/bin/sessions_spawn and /workspace/lib/sessions_spawn.py"
echo "Setup complete."