import os
import json
import random
import stat

random.seed(42)

WORKSPACE = "/workspace"

# ── 1. Build the auto-test-generator skill (the tool itself) ──────────────────
atg_dir = os.path.join(WORKSPACE, "skills", "auto-test-generator")
os.makedirs(atg_dir, exist_ok=True)

# The actual auto-test-generator index.js
atg_index = r"""#!/usr/bin/env node
'use strict';

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const skillName = process.argv[2];
if (!skillName) {
  console.error('Usage: node skills/auto-test-generator/index.js <skill-name>');
  process.exit(1);
}

const skillDir  = path.join(__dirname, '..', skillName);
const indexFile = path.join(skillDir, 'index.js');
const testFile  = path.join(skillDir, 'test.js');

if (!fs.existsSync(indexFile)) {
  console.error(`Skill index not found: ${indexFile}`);
  process.exit(1);
}

// --- Analyse exports ---
const src = fs.readFileSync(indexFile, 'utf8');
const exportedNames = [];
const re = /module\.exports\s*=\s*\{([^}]+)\}/s;
const m  = src.match(re);
if (m) {
  m[1].split(',').forEach(tok => {
    const name = tok.trim().split(/\s*:/)[0].trim();
    if (name) exportedNames.push(name);
  });
}

// --- Generate test.js ---
let testSrc = `'use strict';\n`;
testSrc    += `const assert = require('assert');\n`;
testSrc    += `const skill  = require('./');\n\n`;
testSrc    += `// Auto-generated by auto-test-generator\n\n`;
testSrc    += `// Test 1: module loads\n`;
testSrc    += `assert(skill, 'Module should load');\n\n`;

exportedNames.forEach(name => {
  testSrc += `// Test: export '${name}' exists\n`;
  testSrc += `assert(typeof skill['${name}'] !== 'undefined', "'${name}' should be exported");\n\n`;
});

// Test --help
testSrc += `// Test 2: --help flag\n`;
testSrc += `const { execSync } = require('child_process');\n`;
testSrc += `try {\n`;
testSrc += `  const out = execSync('node ' + __dirname + '/index.js --help', { timeout: 5000 }).toString();\n`;
testSrc += `  assert(out.length > 0, '--help should produce output');\n`;
testSrc += `} catch(e) {\n`;
testSrc += `  // --help may exit non-zero; just check stderr/stdout has content\n`;
testSrc += `  const combined = (e.stdout || '') + (e.stderr || '');\n`;
testSrc += `  assert(combined.length > 0, '--help should produce some output');\n`;
testSrc += `}\n\n`;
testSrc += `console.log('All tests passed for skill: ${skillName}');\n`;

fs.writeFileSync(testFile, testSrc, 'utf8');
console.log(`Generated: ${testFile}`);

// --- Run the test ---
try {
  const result = execSync(`node ${testFile}`, { cwd: skillDir, timeout: 15000 }).toString();
  console.log(result);
  console.log('SUCCESS');
} catch (err) {
  console.error('FAILURE:', err.stderr ? err.stderr.toString() : err.message);
  process.exit(1);
}
"""

with open(os.path.join(atg_dir, "index.js"), "w") as f:
    f.write(atg_index)

# ── 2. Build the TARGET skill: data-formatter ─────────────────────────────────
# This skill exists but has no tests yet. It has a valid index.js with exports.
df_dir = os.path.join(WORKSPACE, "skills", "data-formatter")
os.makedirs(df_dir, exist_ok=True)

df_index = r"""#!/usr/bin/env node
'use strict';

/**
 * data-formatter skill
 * Provides utilities for formatting and transforming data payloads.
 */

function formatJSON(data) {
  return JSON.stringify(data, null, 2);
}

function toCSV(rows) {
  if (!rows || rows.length === 0) return '';
  const headers = Object.keys(rows[0]);
  const lines   = rows.map(r => headers.map(h => r[h]).join(','));
  return [headers.join(','), ...lines].join('\n');
}

function normalize(str) {
  return str.trim().toLowerCase().replace(/\s+/g, '_');
}

if (require.main === module) {
  const args = process.argv.slice(2);
  if (args[0] === '--help' || args.length === 0) {
    console.log('Usage: node skills/data-formatter/index.js [--help]');
    console.log('Exports: formatJSON, toCSV, normalize');
  }
}

module.exports = { formatJSON, toCSV, normalize };
"""

with open(os.path.join(df_dir, "index.js"), "w") as f:
    f.write(df_index)

# ── 3. Distractor files ───────────────────────────────────────────────────────
# Populate the workspace with realistic distractor noise

distractor_skills = [
    ("skill-health-monitor", "healthCheck", "Monitors service health endpoints"),
    ("skill-logger",         "log",         "Structured logging utility"),
    ("skill-cache",          "get,set,del",  "In-memory cache abstraction"),
    ("skill-config-loader",  "loadConfig",  "Loads YAML/JSON configs"),
    ("skill-notifier",       "notify",      "Sends notifications to channels"),
]

for (name, exports_raw, desc) in distractor_skills:
    d = os.path.join(WORKSPACE, "skills", name)
    os.makedirs(d, exist_ok=True)
    export_entries = ", ".join([f"{e.strip()}: function() {{}}" for e in exports_raw.split(",")])
    content = f"""'use strict';
// {desc}
module.exports = {{ {export_entries} }};
"""
    with open(os.path.join(d, "index.js"), "w") as f:
        f.write(content)

    # Some already have test.js (but for data-formatter there should be none)
    if name in ("skill-health-monitor", "skill-logger"):
        with open(os.path.join(d, "test.js"), "w") as f:
            f.write("'use strict';\nconst assert = require('assert');\nconsole.log('existing test ok');\n")

    # Each distractor has a README
    with open(os.path.join(d, "README.md"), "w") as f:
        f.write(f"# {name}\n{desc}\n")

# Top-level distractor files
toplevel_files = {
    "package.json": json.dumps({
        "name": "openclaw-skills",
        "version": "1.0.0",
        "description": "OpenClaw skill registry",
        "scripts": {
            "test": "echo 'run per-skill tests'"
        }
    }, indent=2),
    "README.md": "# OpenClaw Skills\nA registry of skills for the OpenClaw framework.\n",
    ".gitignore": "node_modules/\n*.log\n",
    "CHANGELOG.md": "## v1.2.0\n- Added data-formatter skill\n- Bugfixes\n",
    "CONTRIBUTING.md": "# Contributing\nPlease ensure all skills have test coverage before submitting a PR.\n",
}

for fname, content in toplevel_files.items():
    with open(os.path.join(WORKSPACE, fname), "w") as f:
        f.write(content)

# config/ directory distractors
cfg_dir = os.path.join(WORKSPACE, "config")
os.makedirs(cfg_dir, exist_ok=True)
with open(os.path.join(cfg_dir, "settings.json"), "w") as f:
    json.dump({"env": "production", "logLevel": "info", "skills": ["data-formatter", "skill-logger"]}, f, indent=2)
with open(os.path.join(cfg_dir, "registry.json"), "w") as f:
    json.dump({"skills": ["auto-test-generator", "data-formatter", "skill-health-monitor"]}, f, indent=2)

# scripts/ directory
scripts_dir = os.path.join(WORKSPACE, "scripts")
os.makedirs(scripts_dir, exist_ok=True)
with open(os.path.join(scripts_dir, "deploy.sh"), "w") as f:
    f.write("#!/bin/bash\necho 'Deploying skills...'\n")
with open(os.path.join(scripts_dir, "lint.sh"), "w") as f:
    f.write("#!/bin/bash\necho 'Linting...'\n")

# docs/ directory
docs_dir = os.path.join(WORKSPACE, "docs")
os.makedirs(docs_dir, exist_ok=True)
with open(os.path.join(docs_dir, "architecture.md"), "w") as f:
    f.write("# Architecture\nSkills are self-contained Node.js modules under skills/.\n")
with open(os.path.join(docs_dir, "testing.md"), "w") as f:
    f.write("# Testing\nEach skill should have a test.js generated via the auto-test-generator.\n")

print("Workspace initialized successfully.")
print("Skills created:")
for entry in os.listdir(os.path.join(WORKSPACE, "skills")):
    print(f"  skills/{entry}")