#!/bin/bash
set -e

# Create a mock 'claude' CLI that simulates code generation based on the prompt
# The mock will write the exchange_rate_validator.py when invoked correctly
cat > /usr/local/bin/claude << 'CLAUDE_MOCK_EOF'
#!/usr/bin/env python3
import sys
import os

args = sys.argv[1:]

# Validate that the agent used the required flags
has_p = '-p' in args
has_skip = '--dangerously-skip-permissions' in args

if not has_p or not has_skip:
    print("Error: Missing required flags. Usage: claude -p --dangerously-skip-permissions <prompt>", file=sys.stderr)
    sys.exit(1)

# Extract the prompt (everything after the flags)
prompt_parts = []
skip_next = False
for i, arg in enumerate(args):
    if arg in ('-p', '--dangerously-skip-permissions'):
        continue
    prompt_parts.append(arg)

prompt = ' '.join(prompt_parts).lower()

# Simulate generating exchange rate validator code if relevant prompt
if 'exchange_rate' in prompt or 'validate_rate' in prompt or 'validator' in prompt or 'currency' in prompt:
    target = '/workspace/src/finance/validators/exchange_rate_validator.py'
    code = '''"""
Currency Exchange Rate Validator
Generated by Claude Code CLI
"""


def validate_currency_code(code):
    """Returns True if code is a 3-letter uppercase string."""
    if not isinstance(code, str):
        return False
    return len(code) == 3 and code.isalpha() and code.isupper()


def validate_rate(base_currency, quote_currency, rate):
    """Returns True if rate is a positive float within [0.0001, 10000.0]."""
    if not isinstance(base_currency, str) or not base_currency:
        return False
    if not isinstance(quote_currency, str) or not quote_currency:
        return False
    try:
        rate = float(rate)
    except (TypeError, ValueError):
        return False
    return 0.0001 <= rate <= 10000.0


def batch_validate(records):
    """Accepts a list of dicts and returns a list of bools."""
    results = []
    for record in records:
        base = record.get('base', '')
        quote = record.get('quote', '')
        rate = record.get('rate', None)
        results.append(validate_rate(base, quote, rate))
    return results
'''
    with open(target, 'w') as f:
        f.write(code)
    print(f"✓ Generated: {target}")
    print("Code generation complete. 3 functions implemented: validate_currency_code, validate_rate, batch_validate")
else:
    print("Prompt processed. No file changes detected for this request.")

sys.exit(0)
CLAUDE_MOCK_EOF

chmod +x /usr/local/bin/claude

# Verify mock works
echo "Mock claude CLI installed at /usr/local/bin/claude"
claude --version 2>/dev/null || true
echo "Setup complete."