import os
import random
import stat

random.seed(42)

workspace = "/workspace"

# --- Create legacy bank app directory structure ---
dirs = [
    "legacy_bank_app",
    "legacy_bank_app/core",
    "legacy_bank_app/core/auth",
    "legacy_bank_app/core/transactions",
    "legacy_bank_app/reporting",
    "legacy_bank_app/reporting/templates",
    "legacy_bank_app/utils",
    "legacy_bank_app/tests",
    "legacy_bank_app/tests/unit",
    "legacy_bank_app/tests/integration",
    "legacy_bank_app/config",
    "legacy_bank_app/migrations",
]
for d in dirs:
    os.makedirs(os.path.join(workspace, d), exist_ok=True)

# --- Distractor legacy Python 2 source files ---
files = {
    "legacy_bank_app/core/auth/login.py": """\
# Python 2 legacy login module
import md5
import urllib2

def authenticate(user, passwd):
    hashed = md5.new(passwd).hexdigest()
    print "Authenticating user:", user
    try:
        resp = urllib2.urlopen("http://internal-auth/check?user=%s&hash=%s" % (user, hashed))
        return resp.read()
    except urllib2.URLError, e:
        print "Auth error:", e
        return None
""",
    "legacy_bank_app/core/transactions/transfer.py": """\
# Python 2 legacy transaction module
from __future__ import print_function
import httplib

def transfer_funds(src, dst, amount):
    print "Transferring %s from %s to %s" % (amount, src, dst)
    conn = httplib.HTTPConnection("internal-bank-api")
    conn.request("POST", "/transfer", "src=%s&dst=%s&amount=%s" % (src, dst, amount))
    resp = conn.getresponse()
    return resp.status
""",
    "legacy_bank_app/core/transactions/batch.py": """\
# Batch processor (Python 2)
import Queue
import thread

def process_batch(items):
    q = Queue.Queue()
    for item in items:
        q.put(item)
    thread.start_new_thread(worker, (q,))

def worker(q):
    while not q.empty():
        item = q.get()
        print "Processing:", item
""",
    "legacy_bank_app/reporting/monthly.py": """\
# Monthly reporting (Python 2)
import cPickle
import StringIO

def generate_report(data):
    buf = StringIO.StringIO()
    cPickle.dump(data, buf)
    return buf.getvalue()
""",
    "legacy_bank_app/reporting/templates/summary.html": """\
<html>
<body>
<h1>Monthly Summary</h1>
<p>Generated by legacy reporting engine</p>
</body>
</html>
""",
    "legacy_bank_app/utils/helpers.py": """\
# Utility helpers (Python 2)
import types

def is_string(val):
    return isinstance(val, types.StringTypes)

def to_unicode(s):
    if isinstance(s, str):
        return s.decode('utf-8')
    return s
""",
    "legacy_bank_app/utils/crypto.py": """\
# Crypto utilities (Python 2)
import sha
import base64

def hash_secret(secret):
    return base64.b64encode(sha.new(secret).digest())
""",
    "legacy_bank_app/tests/unit/test_auth.py": """\
# Unit tests (Python 2 unittest)
import unittest

class TestAuth(unittest.TestCase):
    def test_hashing(self):
        self.assertEqual(len('abc'), 3)

if __name__ == '__main__':
    unittest.main()
""",
    "legacy_bank_app/tests/integration/test_transfer.py": """\
# Integration test stub
def test_full_transfer():
    pass
""",
    "legacy_bank_app/config/settings.py": """\
# Legacy settings (Python 2 style)
DATABASE = {
    'host': 'localhost',
    'port': 5432,
    'name': 'bank_legacy_db',
}
DEBUG = True
SECRET_KEY = 'legacy-insecure-key-1234'
""",
    "legacy_bank_app/migrations/001_initial.sql": """\
CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    owner VARCHAR(255),
    balance NUMERIC(15,2)
);
""",
    "legacy_bank_app/migrations/002_add_transactions.sql": """\
CREATE TABLE transactions (
    id SERIAL PRIMARY KEY,
    src_account INTEGER,
    dst_account INTEGER,
    amount NUMERIC(15,2),
    timestamp TIMESTAMPTZ DEFAULT NOW()
);
""",
}

for path, content in files.items():
    full_path = os.path.join(workspace, path)
    with open(full_path, "w") as f:
        f.write(content)

# --- Create mock state directory for the process/codex mocks ---
state_dir = "/tmp/codex_mock_state"
os.makedirs(state_dir, exist_ok=True)

print("Workspace and legacy app files created successfully.")
print(f"Files created: {len(files)}")