import os
import random
from pathlib import Path
from datetime import date

random.seed(42)

WORKSPACE = Path(os.environ.get("WORKSPACE", "/workspace"))

# Use a fixed test date
TEST_DATE = "2025-06-10"

# ── Directory skeleton (distractors) ──────────────────────────────────────────
dirs = [
    "memory",
    "vault/daily-recap",
    "vault/projects/athena",
    "vault/projects/hermes",
    "vault/skills/web-search",
    "vault/skills/code-runner",
    "vault/inbox",
    "vault/templates",
    "logs/cron",
    "logs/errors",
    "scripts",
    "config",
]
for d in dirs:
    (WORKSPACE / d).mkdir(parents=True, exist_ok=True)

# ── Distractor files ──────────────────────────────────────────────────────────

# Older memory logs (distractors)
for past_date in ["2025-06-07", "2025-06-08", "2025-06-09"]:
    (WORKSPACE / f"memory/{past_date}.md").write_text(
        f"# Memory Log {past_date}\n\n- Routine tasks completed.\n- No major activity.\n"
    )

# Older vault recap entries (distractors, different dates)
for past_date in ["2025-06-07", "2025-06-08", "2025-06-09"]:
    (WORKSPACE / f"vault/daily-recap/{past_date}.md").write_text(
        f"---\ndate: {past_date}\ntime: 23:59 ET\ntype: daily-recap\nsource: agent\ntags: [daily-recap, routine]\n---\n\n# Daily Recap — {past_date}\n\n## Requests & Tasks\n- Routine.\n\n---\n*Auto-generated by Atlas at end of day.*\n"
    )

# Vault project files
(WORKSPACE / "vault/projects/athena/overview.md").write_text(
    "# Project Athena\n\nAI-driven data pipeline for internal metrics.\n"
)
(WORKSPACE / "vault/projects/hermes/notes.md").write_text(
    "# Hermes Notes\n\nMessaging layer redesign ideas.\n"
)

# Skill docs
(WORKSPACE / "vault/skills/web-search/README.md").write_text(
    "# Web Search Skill\n\nSearch the web for recent info.\n"
)
(WORKSPACE / "vault/skills/code-runner/README.md").write_text(
    "# Code Runner Skill\n\nExecute sandboxed Python snippets.\n"
)

# Templates (distractor)
(WORKSPACE / "vault/templates/meeting-notes.md").write_text(
    "# Meeting Notes Template\n\n## Attendees\n## Action Items\n"
)

# Config files
(WORKSPACE / "config/agent.yaml").write_text(
    "agent:\n  name: Atlas\n  timezone: ET\n  vault_path: vault/\n"
)
(WORKSPACE / "config/cron.conf").write_text(
    "59 23 * * * /scripts/nightly_recap.sh\n"
)

# Scripts
(WORKSPACE / "scripts/nightly_recap.sh").write_text(
    "#!/bin/bash\n# Placeholder nightly recap trigger\necho 'Recap triggered'\n"
)

# Cron logs
(WORKSPACE / "logs/cron/2025-06-09.log").write_text(
    "[23:59:01] Recap completed successfully.\n"
)
(WORKSPACE / "logs/errors/2025-06-08.log").write_text(
    "[02:14:55] Minor timeout on web-search skill. Recovered.\n"
)

# Inbox
(WORKSPACE / "vault/inbox/unprocessed-notes.md").write_text(
    "# Inbox\n\n- Look into LLM fine-tuning cost comparisons.\n- Check calendar API integration.\n"
)

# ── TODAY'S MEMORY LOG (the real input the agent must read) ───────────────────
memory_log = f"""# Memory Log {TEST_DATE}

## 09:12 — Request
Ryan asked: "can you research the best open-source vector databases for a RAG pipeline and give me a comparison"

## 09:45 — Research
Investigated Chroma, Weaviate, Qdrant, Milvus, and pgvector. Key finding: Qdrant has the best Rust-native performance for high-throughput, Chroma is simplest for local dev, pgvector best for teams already on Postgres.

## 10:30 — Request
Ryan asked: "build a quick Python script that benchmarks insertion speed for Chroma vs Qdrant locally"

## 11:05 — Built
Created scripts/bench_vectordb.py — runs 10k insertion benchmark with timing output for Chroma and Qdrant.

## 13:20 — Request
Ryan asked: "update the Athena project overview with the vector DB decision"

## 13:35 — Built / Modified
Updated vault/projects/athena/overview.md to include vector DB selection rationale (chose Qdrant for production, Chroma for dev/test).

## 14:50 — Research
Looked into Qdrant's snapshot/backup API. Found that snapshots can be triggered via REST and stored locally; no cloud dependency required.

## 16:10 — Decision
Decided to proceed with Qdrant for Project Athena's production vector store. Chroma retained for local developer environments.

## 17:30 — Notable
Ryan mentioned wanting to explore LLM fine-tuning costs next week. Flagged for follow-up.

## 18:00 — Error / Notable
Encountered an intermittent timeout when calling Qdrant health-check endpoint during benchmark — likely a Docker networking issue on Ryan's machine. Logged in errors.
"""
(WORKSPACE / f"memory/{TEST_DATE}.md").write_text(memory_log)

# ── PRE-EXISTING PARTIAL VAULT ENTRY (the "never overwrite" trap) ─────────────
# This simulates an earlier partial recap written at midday — agent MUST append
# an Addendum, not overwrite.
existing_entry = f"""---
date: {TEST_DATE}
time: 13:00 ET
type: daily-recap
source: agent
tags: [daily-recap, vector-database, rag]
---

# Daily Recap — {TEST_DATE}

## Requests & Tasks
- Researched open-source vector databases for RAG pipeline comparison.

## Research
- Compared Chroma, Weaviate, Qdrant, Milvus, pgvector; Qdrant top for throughput.

## Built / Created
- scripts/bench_vectordb.py: insertion benchmark for Chroma vs Qdrant.

## Decisions & Outcomes
- (In progress — afternoon session pending)

## Notable
- (Pending end-of-day)

---
*Auto-generated by Atlas at end of day.*
"""
(WORKSPACE / f"vault/daily-recap/{TEST_DATE}.md").write_text(existing_entry)

print(f"[gen_inputs] Workspace prepared at {WORKSPACE}")
print(f"[gen_inputs] Test date: {TEST_DATE}")
print(f"[gen_inputs] Memory log: memory/{TEST_DATE}.md")
print(f"[gen_inputs] Pre-existing vault entry: vault/daily-recap/{TEST_DATE}.md")